<?php

function themo_icons() {
    return [
        'th-trip travelpack-aqualung-bottles' => 'aqualung-bottles',
        'th-trip travelpack-baseball-headgear' => 'baseball-headgear',
        'th-trip travelpack-beach-bag' => 'each-bag',
        'th-trip travelpack-beach-ball' => 'beach-ball',
        'th-trip travelpack-beach-mattress' => 'beach-mattress',
        'th-trip travelpack-big-trip-caravan' => 'big-trip-caravan',
        'th-trip travelpack-binoculars' => 'binoculars',
        'th-trip travelpack-boat-anchor' => 'boat-anchor',
        'th-trip travelpack-cableway-lift' => 'cableway-lift',
        'th-trip travelpack-cadillac-car' => 'cadillac-car',
        'th-trip travelpack-camel-walking' => 'camel-walking',
        'th-trip travelpack-camping-tent' => 'camping-tent',
        'th-trip travelpack-car-trip' => 'car-trip',
        'th-trip travelpack-carnival-masks' => 'carnival-masks',
        'th-trip travelpack-circular-watch' => 'circular-watch',
        'th-trip travelpack-concert-tickets' => 'oncert-tickets',
        'th-trip travelpack-construction-jacket' => 'construction-jacket',
        'th-trip travelpack-cruise-liner-boat' => 'ruise-liner-boat',
        'th-trip travelpack-digital-photography-camera' => 'digital-photography-camera',
        'th-trip travelpack-direction-sign' => 'direction-sign',
        'th-trip travelpack-double-dice' => 'double-dice',
        'th-trip travelpack-dubai-burj-al-arab' => 'dubai-burj-al-arab',
        'th-trip travelpack-extensible-pirate-spyglass' => 'extensible-pirate-spyglass',
        'th-trip travelpack-female-swim-suit' => 'female-swim-suit',
        'th-trip travelpack-film-roll' => 'film-roll',
        'th-trip travelpack-flip-flops-top-view' => 'flip-flops-top-view',
        'th-trip travelpack-flippers' => 'flippers',
        'th-trip travelpack-flying-helicopter' => 'flying-helicopter',
        'th-trip travelpack-flying-kite' => 'flying-kite',
        'th-trip travelpack-fork-plate-knife' => 'fork-plate-knife',
        'th-trip travelpack-french-eiffel-tower' => 'french-eiffel-tower',
        'th-trip travelpack-frontal-reflex-camera' => 'frontal-reflex-camera',
        'th-trip travelpack-frontal-school-bus' => 'frontal-school-bus',
        'th-trip travelpack-frontal-train' => 'frontal-train',
        'th-trip travelpack-frontal-video-camera' => 'frontal-video-camera',
        'th-trip travelpack-gym-dumbbell' => 'gym-dumbbell',
        'th-trip travelpack-hand-fan' => 'hand-fan',
        'th-trip travelpack-hanger-with-towel' => 'hanger-with-towel',
        'th-trip travelpack-high-speed-train' => 'high-speed-train',
        'th-trip travelpack-hot-air-baloon-flying' => 'hot-air-baloon-flying',
        'th-trip travelpack-hotel-key' => 'hotel-key',
        'th-trip travelpack-indian-tent' => 'indian-tent',
        'th-trip travelpack-inflatable-boat-top-view' => 'inflatable-boat-top-view',
        'th-trip travelpack-jellyfish' => 'jellyfish',
        'th-trip travelpack-journey-bag' => 'journey-bag',
        'th-trip travelpack-kayak-top-view' => 'kayak-top-view',
        'th-trip travelpack-king-size-bed' => 'king-size-bed',
        'th-trip travelpack-lifebuoy' => 'lifebuoy',
        'th-trip travelpack-luggage-cart' => 'luggage-cart',
        'th-trip travelpack-map-pin' => 'map-pin',
        'th-trip travelpack-martini-glass' => 'martini-glass',
        'th-trip travelpack-mosque-construction' => 'mosque-construction',
        'th-trip travelpack-motorbiking-trip' => 'motorbiking-trip',
        'th-trip travelpack-motorcycle-helmet' => 'motorcycle-helmet',
        'th-trip travelpack-mountains-with-snow' => 'mountains-with-snow',
        'th-trip travelpack-movie-photogram' => 'movie-photogram',
        'th-trip travelpack-open-umbrella' => 'open-umbrella',
        'th-trip travelpack-orientation-compass' => 'orientation-compass',
        'th-trip travelpack-party-drink' => 'party-drink',
        'th-trip travelpack-passports' => 'passports',
        'th-trip travelpack-petrol-station' => 'petrol-station',
        'th-trip travelpack-ping-pong-rackets' => 'ping-pong-rackets',
        'th-trip travelpack-pisa-tower' => 'pisa-tower',
        'th-trip travelpack-polaroid-pictures' => 'polaroid-pictures',
        'th-trip travelpack-postal-stamp' => 'postal-stamp',
        'th-trip travelpack-pyramids-of-egypt' => 'pyramids-of-egypt',
        'th-trip travelpack-reading-glasses' => 'reading-glasses',
        'th-trip travelpack-reception-bell' => 'reception-bell',
        'th-trip travelpack-retro-bicycle' => 'retro-bicycle',
        'th-trip travelpack-room-service' => 'room-service',
        'th-trip travelpack-safety-box' => 'safety-box',
        'th-trip travelpack-sailing-yacht' => 'sailing-yacht',
        'th-trip travelpack-scooter' => 'scooter',
        'th-trip travelpack-scuba-mask' => 'scuba-mask',
        'th-trip travelpack-sea-horse' => 'sea-horse',
        'th-trip travelpack-sea-shell' => 'sea-shell',
        'th-trip travelpack-ship-steering-wheel' => 'ship-steering-wheel',
        'th-trip travelpack-shower-head-running-water' => 'shower-head-running-water',
        'th-trip travelpack-skis-and-sticks' => 'skis-and-sticks',
        'th-trip travelpack-snowboard-with-boot' => 'snowboard-with-boot',
        'th-trip travelpack-snowmobile' => 'snowmobile',
        'th-trip travelpack-starfish' => 'starfish',
        'th-trip travelpack-suitcase-with-wheels' => 'suitcase-with-wheels',
        'th-trip travelpack-suitcase-with-wheels-1' => 'suitcase-with-wheels-1',
        'th-trip travelpack-summer-sun' => 'summer-sun',
        'th-trip travelpack-sunbed' => 'sunbed',
        'th-trip travelpack-surf-board' => 'surf-board',
        'th-trip travelpack-swimming-trunks' => 'swimming-trunks',
        'th-trip travelpack-taxi-sign' => 'taxi-sign',
        'th-trip travelpack-tennis-equipment' => 'tennis-equipment',
        'th-trip travelpack-travelling-backpack' => 'travelling-backpack',
        'th-trip travelpack-trifolded-map-route' => 'trifolded-map-route',
        'th-trip travelpack-trip-bag' => 'trip-bag',
        'th-trip travelpack-tropical-fish' => 'tropical-fish',
        'th-trip travelpack-two-credit-cards' => 'two-credit-cards',
        'th-trip travelpack-two-palm-trees-island' => 'two-palm-trees-island',
        'th-trip travelpack-women-hat' => 'women-hat',
        'th-trip travelpack-world-wide-web' => 'world-wide-web',
        /* Linea Arrows */
        'icon-arrows-anticlockwise' => 'arrows-anticlockwise',
        'icon-arrows-anticlockwise-dashed' => 'arrows-anticlockwise-dashed',
        'icon-arrows-button-down' => 'arrows-button-down',
        'icon-arrows-button-off' => 'arrows-button-off',
        'icon-arrows-button-on' => 'arrows-button-on',
        'icon-arrows-button-up' => 'arrows-button-up',
        'icon-arrows-check' => 'arrows-check',
        'icon-arrows-circle-check' => 'arrows-circle-check',
        'icon-arrows-circle-down' => 'arrows-circle-down',
        'icon-arrows-circle-downleft' => 'arrows-circle-downleft',
        'icon-arrows-circle-downright' => 'arrows-circle-downright',
        'icon-arrows-circle-left' => 'arrows-circle-left',
        'icon-arrows-circle-minus' => 'arrows-circle-minus',
        'icon-arrows-circle-plus' => 'arrows-circle-plus',
        'icon-arrows-circle-remove' => 'arrows-circle-remove',
        'icon-arrows-circle-right' => 'arrows-circle-right',
        'icon-arrows-circle-up' => 'arrows-circle-up',
        'icon-arrows-circle-upleft' => 'arrows-circle-upleft',
        'icon-arrows-circle-upright' => 'arrows-circle-upright',
        'icon-arrows-clockwise' => 'arrows-clockwise',
        'icon-arrows-clockwise-dashed' => 'arrows-clockwise-dashed',
        'icon-arrows-compress' => 'arrows-compress',
        'icon-arrows-deny' => 'arrows-deny',
        'icon-arrows-diagonal' => 'arrows-diagonal',
        'icon-arrows-diagonal2' => 'icon-arrows-diagonal2',
        'icon-arrows-down' => 'arrows-down',
        'icon-arrows-down-double' => 'arrows-down-double',
        'icon-arrows-downleft' => 'arrows-downleft',
        'icon-arrows-downright' => 'arrows-downright',
        'icon-arrows-drag-down' => 'arrows-drag-down',
        'icon-arrows-drag-down-dashed' => 'arrows-drag-down-dashed',
        'icon-arrows-drag-horiz' => 'arrows-drag-horiz',
        'icon-arrows-drag-left' => 'arrows-drag-left',
        'icon-arrows-drag-left-dashed' => 'arrows-drag-left-dashed',
        'icon-arrows-drag-right' => 'arrows-drag-right',
        'icon-arrows-drag-right-dashed' => 'arrows-drag-right-dashed',
        'icon-arrows-drag-up' => 'arrows-drag-up',
        'icon-arrows-drag-up-dashed' => 'arrows-drag-up-dashed',
        'icon-arrows-drag-vert' => 'arrows-drag-vert',
        'icon-arrows-exclamation' => 'arrows-exclamation',
        'icon-arrows-expand' => 'arrows-expand',
        'icon-arrows-expand-diagonal1' => 'arrows-expand-diagonal1',
        'icon-arrows-expand-horizontal1' => 'arrows-expand-horizontal1',
        'icon-arrows-expand-vertical1' => 'arrows-expand-vertical1',
        'icon-arrows-fit-horizontal' => 'arrows-fit-horizontal',
        'icon-arrows-fit-vertical' => 'arrows-fit-vertical',
        'icon-arrows-glide' => 'arrows-glide',
        'icon-arrows-glide-horizontal' => 'arrows-glide-horizontal',
        'icon-arrows-glide-vertical' => 'arrows-glide-vertical',
        'icon-arrows-hamburger1' => 'icon-arrows-hamburger1',
        'icon-arrows-hamburger-2' => 'arrows-hamburger-2',
        'icon-arrows-horizontal' => 'arrows-horizontal',
        'icon-arrows-info' => 'arrows-info',
        'icon-arrows-keyboard-alt' => 'arrows-keyboard-alt',
        'icon-arrows-keyboard-cmd' => 'arrows-keyboard-cmd',
        'icon-arrows-keyboard-delete' => 'arrows-keyboard-delete',
        'icon-arrows-keyboard-down' => 'arrows-keyboard-down',
        'icon-arrows-keyboard-left' => 'arrows-keyboard-left',
        'icon-arrows-keyboard-return' => 'arrows-keyboard-return',
        'icon-arrows-keyboard-right' => 'arrows-keyboard-right',
        'icon-arrows-keyboard-shift' => 'arrows-keyboard-shift',
        'icon-arrows-keyboard-tab' => 'arrows-keyboard-tab',
        'icon-arrows-keyboard-up' => 'arrows-keyboard-up',
        'icon-arrows-left' => 'arrows-left',
        'icon-arrows-left-double-32' => 'arrows-left-double-32',
        'icon-arrows-minus' => 'arrows-minus',
        'icon-arrows-move' => 'arrows-move',
        'icon-arrows-move2' => 'icon-arrows-move2',
        'icon-arrows-move-bottom' => 'arrows-move-bottom',
        'icon-arrows-move-left' => 'arrows-move-left',
        'icon-arrows-move-right' => 'arrows-move-right',
        'icon-arrows-move-top' => 'arrows-move-top',
        'icon-arrows-plus' => 'arrows-plus',
        'icon-arrows-question' => 'arrows-question',
        'icon-arrows-remove' => 'arrows-remove',
        'icon-arrows-right' => 'arrows-right',
        'icon-arrows-right-double' => 'arrows-right-double',
        'icon-arrows-rotate' => 'arrows-rotate',
        'icon-arrows-rotate-anti' => 'arrows-rotate-anti',
        'icon-arrows-rotate-anti-dashed' => 'arrows-rotate-anti-dashed',
        'icon-arrows-rotate-dashed' => 'arrows-rotate-dashed',
        'icon-arrows-shrink' => 'arrows-shrink',
        'icon-arrows-shrink-diagonal1' => 'arrows-shrink-diagonal1',
        'icon-arrows-shrink-diagonal2' => 'arrows-shrink-diagonal2',
        'icon-arrows-shrink-horizonal2' => 'arrows-shrink-horizonal2',
        'icon-arrows-shrink-horizontal1' => 'arrows-shrink-horizontal1',
        'icon-arrows-shrink-vertical1' => 'arrows-shrink-vertical1',
        'icon-arrows-shrink-vertical2' => 'arrows-shrink-vertical2',
        'icon-arrows-sign-down' => 'arrows-sign-down',
        'icon-arrows-sign-left' => 'arrows-sign-left',
        'icon-arrows-sign-right' => 'arrows-sign-right',
        'icon-arrows-sign-up' => 'arrows-sign-up',
        'icon-arrows-slide-down1' => 'arrows-slide-down1',
        'icon-arrows-slide-down2' => 'arrows-slide-down2',
        'icon-arrows-slide-left1' => 'arrows-slide-left1',
        'icon-arrows-slide-left2' => 'arrows-slide-left2',
        'icon-arrows-slide-right1' => 'arrows-slide-right1',
        'icon-arrows-slide-right2' => 'arrows-slide-right2',
        'icon-arrows-slide-up1' => 'arrows-slide-up1',
        'icon-arrows-slide-up2' => 'arrows-slide-up2',
        'icon-arrows-slim-down' => 'arrows-slim-down',
        'icon-arrows-slim-down-dashed' => 'arrows-slim-down-dashed',
        'icon-arrows-slim-left' => 'arrows-slim-left',
        'icon-arrows-slim-left-dashed' => 'arrows-slim-left-dashed',
        'icon-arrows-slim-right' => 'arrows-slim-right',
        'icon-arrows-slim-right-dashed' => 'arrows-slim-right-dashed',
        'icon-arrows-slim-up' => 'arrows-slim-up',
        'icon-arrows-slim-up-dashed' => 'arrows-slim-up-dashed',
        'icon-arrows-square-check' => 'arrows-square-check',
        'icon-arrows-square-down' => 'arrows-square-down',
        'icon-arrows-square-downleft' => 'arrows-square-downleft',
        'icon-arrows-square-downright' => 'arrows-square-downright',
        'icon-arrows-square-left' => 'arrows-square-left',
        'icon-arrows-square-minus' => 'arrows-square-minus',
        'icon-arrows-square-plus' => 'arrows-square-plus',
        'icon-arrows-square-remove' => 'arrows-square-remove',
        'icon-arrows-square-right' => 'arrows-square-right',
        'icon-arrows-square-up' => 'arrows-square-up',
        'icon-arrows-square-upleft' => 'arrows-square-upleft',
        'icon-arrows-square-upright' => 'arrows-square-upright',
        'icon-arrows-squares' => 'arrows-squares',
        'icon-arrows-stretch-diagonal1' => 'arrows-stretch-diagonal1',
        'icon-arrows-stretch-diagonal2' => 'arrows-stretch-diagonal2',
        'icon-arrows-stretch-diagonal3' => 'arrows-stretch-diagonal3',
        'icon-arrows-stretch-diagonal4' => 'arrows-stretch-diagonal4',
        'icon-arrows-stretch-horizontal1' => 'arrows-stretch-horizontal1',
        'icon-arrows-stretch-horizontal2' => 'arrows-stretch-horizontal2',
        'icon-arrows-stretch-vertical1' => 'arrows-stretch-vertical1',
        'icon-arrows-stretch-vertical2' => 'arrows-stretch-vertical2',
        'icon-arrows-switch-horizontal' => 'arrows-switch-horizontal',
        'icon-arrows-switch-vertical' => 'arrows-switch-vertical',
        'icon-arrows-up' => 'arrows-up',
        'icon-arrows-up-double-33' => 'arrows-up-double-33',
        'icon-arrows-upleft' => 'arrows-upleft',
        'icon-arrows-upright' => 'arrows-upright',
        'icon-arrows-vertical' => 'arrows-vertical',
        /* Linea Basic */
        'icon-basic-accelerator' => 'basic-accelerator',
        'icon-basic-alarm' => 'basic-alarm',
        'icon-basic-anchor' => 'basic-anchor',
        'icon-basic-anticlockwise' => 'basic-anticlockwise',
        'icon-basic-archive' => 'basic-archive',
        'icon-basic-archive-full' => 'basic-archive-full',
        'icon-basic-ban' => 'basic-ban',
        'icon-basic-battery-charge' => 'basic-battery-charge',
        'icon-basic-battery-empty' => 'basic-battery-empty',
        'icon-basic-battery-full' => 'basic-battery-full',
        'icon-basic-battery-half' => 'basic-battery-half',
        'icon-basic-bolt' => 'basic-bolt',
        'icon-basic-book' => 'basic-book',
        'icon-basic-book-pen' => 'basic-book-pen',
        'icon-basic-book-pencil' => 'basic-book-pencil',
        'icon-basic-bookmark' => 'basic-bookmark',
        'icon-basic-calculator' => 'basic-calculator',
        'icon-basic-calendar' => 'basic-calendar',
        'icon-basic-cards-diamonds' => 'basic-cards-diamonds',
        'icon-basic-cards-hearts' => 'basic-cards-hearts',
        'icon-basic-case' => 'basic-case',
        'icon-basic-chronometer' => 'basic-chronometer',
        'icon-basic-clessidre' => 'basic-clessidre',
        'icon-basic-clock' => 'basic-clock',
        'icon-basic-clockwise' => 'basic-clockwise',
        'icon-basic-cloud' => 'basic-cloud',
        'icon-basic-clubs' => 'basic-clubs',
        'icon-basic-compass' => 'basic-compass',
        'icon-basic-cup' => 'basic-cup',
        'icon-basic-diamonds' => 'basic-diamonds',
        'icon-basic-display' => 'basic-display',
        'icon-basic-download' => 'basic-download',
        'icon-basic-exclamation' => 'basic-exclamation',
        'icon-basic-eye' => 'basic-eye',
        'icon-basic-eye-closed' => 'basic-eye-closed',
        'icon-basic-female' => 'basic-female',
        'icon-basic-flag1' => 'icon-basic-flag1',
        'icon-basic-flag2' => 'icon-basic-flag2',
        'icon-basic-floppydisk' => 'basic-floppydisk',
        'icon-basic-folder' => 'basic-folder',
        'icon-basic-folder-multiple' => 'basic-folder-multiple',
        'icon-basic-gear' => 'basic-gear',
        'icon-basic-geolocalize-01' => 'basic-geolocalize-01',
        'icon-basic-geolocalize-05' => 'basic-geolocalize-05',
        'icon-basic-globe' => 'basic-globe',
        'icon-basic-gunsight' => 'basic-gunsight',
        'icon-basic-hammer' => 'basic-hammer',
        'icon-basic-headset' => 'basic-headset',
        'icon-basic-heart' => 'basic-heart',
        'icon-basic-heart-broken' => 'basic-heart-broken',
        'icon-basic-helm' => 'basic-helm',
        'icon-basic-home' => 'basic-home',
        'icon-basic-info' => 'basic-info',
        'icon-basic-ipod' => 'basic-ipod',
        'icon-basic-joypad' => 'basic-joypad',
        'icon-basic-key' => 'basic-key',
        'icon-basic-keyboard' => 'basic-keyboard',
        'icon-basic-laptop' => 'basic-laptop',
        'icon-basic-life-buoy' => 'basic-life-buoy',
        'icon-basic-lightbulb' => 'basic-lightbulb',
        'icon-basic-link' => 'basic-link',
        'icon-basic-lock' => 'basic-lock',
        'icon-basic-lock-open' => 'basic-lock-open',
        'icon-basic-magic-mouse' => 'basic-magic-mouse',
        'icon-basic-magnifier' => 'basic-magnifier',
        'icon-basic-magnifier-minus' => 'basic-magnifier-minus',
        'icon-basic-magnifier-plus' => 'basic-magnifier-plus',
        'icon-basic-mail' => 'basic-mail',
        'icon-basic-mail-multiple' => 'basic-mail-multiple',
        'icon-basic-mail-open' => 'basic-mail-open',
        'icon-basic-mail-open-text' => 'basic-mail-open-text',
        'icon-basic-male' => 'basic-male',
        'icon-basic-map' => 'basic-map',
        'icon-basic-message' => 'basic-message',
        'icon-basic-message-multiple' => 'basic-message-multiple',
        'icon-basic-message-txt' => 'basic-message-txt',
        'icon-basic-mixer2' => 'icon-basic-mixer2',
        'icon-basic-mouse' => 'basic-mouse',
        'icon-basic-notebook' => 'basic-notebook',
        'icon-basic-notebook-pen' => 'basic-notebook-pen',
        'icon-basic-notebook-pencil' => 'basic-notebook-pencil',
        'icon-basic-paperplane' => 'basic-paperplane',
        'icon-basic-pencil-ruler' => 'basic-pencil-ruler',
        'icon-basic-pencil-ruler-pen' => 'basic-pencil-ruler-pen',
        'icon-basic-photo' => 'basic-photo',
        'icon-basic-picture' => 'basic-picture',
        'icon-basic-picture-multiple' => 'basic-picture-multiple',
        'icon-basic-pin1' => 'icon-basic-pin1',
        'icon-basic-pin2' => 'icon-basic-pin2',
        'icon-basic-postcard' => 'basic-postcard',
        'icon-basic-postcard-multiple' => 'basic-postcard-multiple',
        'icon-basic-printer' => 'basic-printer',
        'icon-basic-question' => 'basic-question',
        'icon-basic-rss' => 'basic-rss',
        'icon-basic-server' => 'basic-server',
        'icon-basic-server2' => 'icon-basic-server2',
        'icon-basic-server-cloud' => 'basic-server-cloud',
        'icon-basic-server-download' => 'basic-server-download',
        'icon-basic-server-upload' => 'basic-server-upload',
        'icon-basic-settings' => 'basic-settings',
        'icon-basic-share' => 'basic-share',
        'icon-basic-sheet' => 'basic-sheet',
        'icon-basic-sheet-multiple' => 'basic-sheet-multiple',
        'icon-basic-sheet-pen' => 'basic-sheet-pen',
        'icon-basic-sheet-pencil' => 'basic-sheet-pencil',
        'icon-basic-sheet-txt' => 'basic-sheet-txt',
        'icon-basic-signs' => 'basic-signs',
        'icon-basic-smartphone' => 'basic-smartphone',
        'icon-basic-spades' => 'basic-spades',
        'icon-basic-spread' => 'basic-spread',
        'icon-basic-spread-bookmark' => 'basic-spread-bookmark',
        'icon-basic-spread-text' => 'basic-spread-text',
        'icon-basic-spread-text-bookmark' => 'basic-spread-text-bookmark',
        'icon-basic-star' => 'basic-star',
        'icon-basic-tablet' => 'basic-tablet',
        'icon-basic-target' => 'basic-target',
        'icon-basic-todo' => 'basic-todo',
        'icon-basic-todo-pen' => 'basic-todo-pen',
        'icon-basic-todo-pencil' => 'basic-todo-pencil',
        'icon-basic-todo-txt' => 'basic-todo-txt',
        'icon-basic-todolist-pen' => 'basic-todolist-pen',
        'icon-basic-todolist-pencil' => 'basic-todolist-pencil',
        'icon-basic-trashcan' => 'basic-trashcan',
        'icon-basic-trashcan-full' => 'basic-trashcan-full',
        'icon-basic-trashcan-refresh' => 'basic-trashcan-refresh',
        'icon-basic-trashcan-remove' => 'basic-trashcan-remove',
        'icon-basic-upload' => 'basic-upload',
        'icon-basic-usb' => 'basic-usb',
        'icon-basic-video' => 'basic-video',
        'icon-basic-watch' => 'basic-watch',
        'icon-basic-webpage' => 'basic-webpage',
        'icon-basic-webpage-img-txt' => 'basic-webpage-img-txt',
        'icon-basic-webpage-multiple' => 'basic-webpage-multiple',
        'icon-basic-webpage-txt' => 'basic-webpage-txt',
        'icon-basic-world' => 'basic-world',
        /* Linea Basic Elaboration */
        'icon-basic-elaboration-bookmark-check' => 'basic-elaboration-bookmark-check',
        'icon-basic-elaboration-bookmark-minus' => 'basic-elaboration-bookmark-minus',
        'icon-basic-elaboration-bookmark-plus' => 'basic-elaboration-bookmark-plus',
        'icon-basic-elaboration-bookmark-remove' => 'basic-elaboration-bookmark-remove',
        'icon-basic-elaboration-briefcase-check' => 'basic-elaboration-briefcase-check',
        'icon-basic-elaboration-briefcase-download' => 'basic-elaboration-briefcase-download',
        'icon-basic-elaboration-briefcase-flagged' => 'basic-elaboration-briefcase-flagged',
        'icon-basic-elaboration-briefcase-minus' => 'basic-elaboration-briefcase-minus',
        'icon-basic-elaboration-briefcase-plus' => 'basic-elaboration-briefcase-plus',
        'icon-basic-elaboration-briefcase-refresh' => 'basic-elaboration-briefcase-refresh',
        'icon-basic-elaboration-briefcase-remove' => 'basic-elaboration-briefcase-remove',
        'icon-basic-elaboration-briefcase-search' => 'basic-elaboration-briefcase-search',
        'icon-basic-elaboration-briefcase-star' => 'basic-elaboration-briefcase-star',
        'icon-basic-elaboration-briefcase-upload' => 'basic-elaboration-briefcase-upload',
        'icon-basic-elaboration-browser-check' => 'basic-elaboration-browser-check',
        'icon-basic-elaboration-browser-download' => 'basic-elaboration-browser-download',
        'icon-basic-elaboration-browser-minus' => 'basic-elaboration-browser-minus',
        'icon-basic-elaboration-browser-plus' => 'basic-elaboration-browser-plus',
        'icon-basic-elaboration-browser-refresh' => 'basic-elaboration-browser-refresh',
        'icon-basic-elaboration-browser-remove' => 'basic-elaboration-browser-remove',
        'icon-basic-elaboration-browser-search' => 'basic-elaboration-browser-search',
        'icon-basic-elaboration-browser-star' => 'basic-elaboration-browser-star',
        'icon-basic-elaboration-browser-upload' => 'basic-elaboration-browser-upload',
        'icon-basic-elaboration-calendar-check' => 'basic-elaboration-calendar-check',
        'icon-basic-elaboration-calendar-cloud' => 'basic-elaboration-calendar-cloud',
        'icon-basic-elaboration-calendar-download' => 'basic-elaboration-calendar-download',
        'icon-basic-elaboration-calendar-empty' => 'basic-elaboration-calendar-empty',
        'icon-basic-elaboration-calendar-flagged' => 'basic-elaboration-calendar-flagged',
        'icon-basic-elaboration-calendar-heart' => 'basic-elaboration-calendar-heart',
        'icon-basic-elaboration-calendar-minus' => 'basic-elaboration-calendar-minus',
        'icon-basic-elaboration-calendar-next' => 'basic-elaboration-calendar-next',
        'icon-basic-elaboration-calendar-noaccess' => 'basic-elaboration-calendar-noaccess',
        'icon-basic-elaboration-calendar-pencil' => 'basic-elaboration-calendar-pencil',
        'icon-basic-elaboration-calendar-plus' => 'basic-elaboration-calendar-plus',
        'icon-basic-elaboration-calendar-previous' => 'basic-elaboration-calendar-previous',
        'icon-basic-elaboration-calendar-refresh' => 'basic-elaboration-calendar-refresh',
        'icon-basic-elaboration-calendar-remove' => 'basic-elaboration-calendar-remove',
        'icon-basic-elaboration-calendar-search' => 'basic-elaboration-calendar-search',
        'icon-basic-elaboration-calendar-star' => 'basic-elaboration-calendar-star',
        'icon-basic-elaboration-calendar-upload' => 'basic-elaboration-calendar-upload',
        'icon-basic-elaboration-cloud-check' => 'basic-elaboration-cloud-check',
        'icon-basic-elaboration-cloud-download' => 'basic-elaboration-cloud-download',
        'icon-basic-elaboration-cloud-minus' => 'basic-elaboration-cloud-minus',
        'icon-basic-elaboration-cloud-noaccess' => 'basic-elaboration-cloud-noaccess',
        'icon-basic-elaboration-cloud-plus' => 'basic-elaboration-cloud-plus',
        'icon-basic-elaboration-cloud-refresh' => 'basic-elaboration-cloud-refresh',
        'icon-basic-elaboration-cloud-remove' => 'basic-elaboration-cloud-remove',
        'icon-basic-elaboration-cloud-search' => 'basic-elaboration-cloud-search',
        'icon-basic-elaboration-cloud-upload' => 'basic-elaboration-cloud-upload',
        'icon-basic-elaboration-document-check' => 'basic-elaboration-document-check',
        'icon-basic-elaboration-document-cloud' => 'basic-elaboration-document-cloud',
        'icon-basic-elaboration-document-download' => 'basic-elaboration-document-download',
        'icon-basic-elaboration-document-flagged' => 'basic-elaboration-document-flagged',
        'icon-basic-elaboration-document-graph' => 'basic-elaboration-document-graph',
        'icon-basic-elaboration-document-heart' => 'basic-elaboration-document-heart',
        'icon-basic-elaboration-document-minus' => 'basic-elaboration-document-minus',
        'icon-basic-elaboration-document-next' => 'basic-elaboration-document-next',
        'icon-basic-elaboration-document-noaccess' => 'basic-elaboration-document-noaccess',
        'icon-basic-elaboration-document-note' => 'basic-elaboration-document-note',
        'icon-basic-elaboration-document-pencil' => 'basic-elaboration-document-pencil',
        'icon-basic-elaboration-document-picture' => 'basic-elaboration-document-picture',
        'icon-basic-elaboration-document-plus' => 'basic-elaboration-document-plus',
        'icon-basic-elaboration-document-previous' => 'basic-elaboration-document-previous',
        'icon-basic-elaboration-document-refresh' => 'basic-elaboration-document-refresh',
        'icon-basic-elaboration-document-remove' => 'basic-elaboration-document-remove',
        'icon-basic-elaboration-document-search' => 'basic-elaboration-document-search',
        'icon-basic-elaboration-document-star' => 'basic-elaboration-document-star',
        'icon-basic-elaboration-document-upload' => 'basic-elaboration-document-upload',
        'icon-basic-elaboration-folder-check' => 'basic-elaboration-folder-check',
        'icon-basic-elaboration-folder-cloud' => 'basic-elaboration-folder-cloud',
        'icon-basic-elaboration-folder-document' => 'basic-elaboration-folder-document',
        'icon-basic-elaboration-folder-download' => 'basic-elaboration-folder-download',
        'icon-basic-elaboration-folder-flagged' => 'basic-elaboration-folder-flagged',
        'icon-basic-elaboration-folder-graph' => 'basic-elaboration-folder-graph',
        'icon-basic-elaboration-folder-heart' => 'basic-elaboration-folder-heart',
        'icon-basic-elaboration-folder-minus' => 'basic-elaboration-folder-minus',
        'icon-basic-elaboration-folder-next' => 'basic-elaboration-folder-next',
        'icon-basic-elaboration-folder-noaccess' => 'basic-elaboration-folder-noaccess',
        'icon-basic-elaboration-folder-note' => 'basic-elaboration-folder-note',
        'icon-basic-elaboration-folder-pencil' => 'basic-elaboration-folder-pencil',
        'icon-basic-elaboration-folder-picture' => 'basic-elaboration-folder-picture',
        'icon-basic-elaboration-folder-plus' => 'basic-elaboration-folder-plus',
        'icon-basic-elaboration-folder-previous' => 'basic-elaboration-folder-previous',
        'icon-basic-elaboration-folder-refresh' => 'basic-elaboration-folder-refresh',
        'icon-basic-elaboration-folder-remove' => 'basic-elaboration-folder-remove',
        'icon-basic-elaboration-folder-search' => 'basic-elaboration-folder-search',
        'icon-basic-elaboration-folder-star' => 'basic-elaboration-folder-star',
        'icon-basic-elaboration-folder-upload' => 'basic-elaboration-folder-upload',
        'icon-basic-elaboration-mail-check' => 'basic-elaboration-mail-check',
        'icon-basic-elaboration-mail-cloud' => 'basic-elaboration-mail-cloud',
        'icon-basic-elaboration-mail-document' => 'basic-elaboration-mail-document',
        'icon-basic-elaboration-mail-download' => 'basic-elaboration-mail-download',
        'icon-basic-elaboration-mail-flagged' => 'basic-elaboration-mail-flagged',
        'icon-basic-elaboration-mail-heart' => 'basic-elaboration-mail-heart',
        'icon-basic-elaboration-mail-next' => 'basic-elaboration-mail-next',
        'icon-basic-elaboration-mail-noaccess' => 'basic-elaboration-mail-noaccess',
        'icon-basic-elaboration-mail-note' => 'basic-elaboration-mail-note',
        'icon-basic-elaboration-mail-pencil' => 'basic-elaboration-mail-pencil',
        'icon-basic-elaboration-mail-picture' => 'basic-elaboration-mail-picture',
        'icon-basic-elaboration-mail-previous' => 'basic-elaboration-mail-previous',
        'icon-basic-elaboration-mail-refresh' => 'basic-elaboration-mail-refresh',
        'icon-basic-elaboration-mail-remove' => 'basic-elaboration-mail-remove',
        'icon-basic-elaboration-mail-search' => 'basic-elaboration-mail-search',
        'icon-basic-elaboration-mail-star' => 'basic-elaboration-mail-star',
        'icon-basic-elaboration-mail-upload' => 'basic-elaboration-mail-upload',
        'icon-basic-elaboration-message-check' => 'basic-elaboration-message-check',
        'icon-basic-elaboration-message-dots' => 'basic-elaboration-message-dots',
        'icon-basic-elaboration-message-happy' => 'basic-elaboration-message-happy',
        'icon-basic-elaboration-message-heart' => 'basic-elaboration-message-heart',
        'icon-basic-elaboration-message-minus' => 'basic-elaboration-message-minus',
        'icon-basic-elaboration-message-note' => 'basic-elaboration-message-note',
        'icon-basic-elaboration-message-plus' => 'basic-elaboration-message-plus',
        'icon-basic-elaboration-message-refresh' => 'basic-elaboration-message-refresh',
        'icon-basic-elaboration-message-remove' => 'basic-elaboration-message-remove',
        'icon-basic-elaboration-message-sad' => 'basic-elaboration-message-sad',
        'icon-basic-elaboration-smartphone-cloud' => 'basic-elaboration-smartphone-cloud',
        'icon-basic-elaboration-smartphone-heart' => 'basic-elaboration-smartphone-heart',
        'icon-basic-elaboration-smartphone-noaccess' => 'basic-elaboration-smartphone-noaccess',
        'icon-basic-elaboration-smartphone-note' => 'basic-elaboration-smartphone-note',
        'icon-basic-elaboration-smartphone-pencil' => 'basic-elaboration-smartphone-pencil',
        'icon-basic-elaboration-smartphone-picture' => 'basic-elaboration-smartphone-picture',
        'icon-basic-elaboration-smartphone-refresh' => 'basic-elaboration-smartphone-refresh',
        'icon-basic-elaboration-smartphone-search' => 'basic-elaboration-smartphone-search',
        'icon-basic-elaboration-tablet-cloud' => 'basic-elaboration-tablet-cloud',
        'icon-basic-elaboration-tablet-heart' => 'basic-elaboration-tablet-heart',
        'icon-basic-elaboration-tablet-noaccess' => 'basic-elaboration-tablet-noaccess',
        'icon-basic-elaboration-tablet-note' => 'basic-elaboration-tablet-note',
        'icon-basic-elaboration-tablet-pencil' => 'basic-elaboration-tablet-pencil',
        'icon-basic-elaboration-tablet-picture' => 'basic-elaboration-tablet-picture',
        'icon-basic-elaboration-tablet-refresh' => 'basic-elaboration-tablet-refresh',
        'icon-basic-elaboration-tablet-search' => 'basic-elaboration-tablet-search',
        'icon-basic-elaboration-todolist-2' => 'basic-elaboration-todolist-2',
        'icon-basic-elaboration-todolist-check' => 'basic-elaboration-todolist-check',
        'icon-basic-elaboration-todolist-cloud' => 'basic-elaboration-todolist-cloud',
        'icon-basic-elaboration-todolist-download' => 'basic-elaboration-todolist-download',
        'icon-basic-elaboration-todolist-flagged' => 'basic-elaboration-todolist-flagged',
        'icon-basic-elaboration-todolist-minus' => 'basic-elaboration-todolist-minus',
        'icon-basic-elaboration-todolist-noaccess' => 'basic-elaboration-todolist-noaccess',
        'icon-basic-elaboration-todolist-pencil' => 'basic-elaboration-todolist-pencil',
        'icon-basic-elaboration-todolist-plus' => 'basic-elaboration-todolist-plus',
        'icon-basic-elaboration-todolist-refresh' => 'basic-elaboration-todolist-refresh',
        'icon-basic-elaboration-todolist-remove' => 'basic-elaboration-todolist-remove',
        'icon-basic-elaboration-todolist-search' => 'basic-elaboration-todolist-search',
        'icon-basic-elaboration-todolist-star' => 'basic-elaboration-todolist-star',
        'icon-basic-elaboration-todolist-upload' => 'basic-elaboration-todolist-upload',
        /* Linea eCommerce */
        'icon-ecommerce-bag' => 'ecommerce-bag',
        'icon-ecommerce-bag-check' => 'ecommerce-bag-check',
        'icon-ecommerce-bag-cloud' => 'ecommerce-bag-cloud',
        'icon-ecommerce-bag-download' => 'ecommerce-bag-download',
        'icon-ecommerce-bag-minus' => 'ecommerce-bag-minus',
        'icon-ecommerce-bag-plus' => 'ecommerce-bag-plus',
        'icon-ecommerce-bag-refresh' => 'ecommerce-bag-refresh',
        'icon-ecommerce-bag-remove' => 'ecommerce-bag-remove',
        'icon-ecommerce-bag-search' => 'ecommerce-bag-search',
        'icon-ecommerce-bag-upload' => 'ecommerce-bag-upload',
        'icon-ecommerce-banknote' => 'ecommerce-banknote',
        'icon-ecommerce-banknotes' => 'ecommerce-banknotes',
        'icon-ecommerce-basket' => 'ecommerce-basket',
        'icon-ecommerce-basket-check' => 'ecommerce-basket-check',
        'icon-ecommerce-basket-cloud' => 'ecommerce-basket-cloud',
        'icon-ecommerce-basket-download' => 'ecommerce-basket-download',
        'icon-ecommerce-basket-minus' => 'ecommerce-basket-minus',
        'icon-ecommerce-basket-plus' => 'ecommerce-basket-plus',
        'icon-ecommerce-basket-refresh' => 'ecommerce-basket-refresh',
        'icon-ecommerce-basket-remove' => 'ecommerce-basket-remove',
        'icon-ecommerce-basket-search' => 'ecommerce-basket-search',
        'icon-ecommerce-basket-upload' => 'ecommerce-basket-upload',
        'icon-ecommerce-bath' => 'ecommerce-bath',
        'icon-ecommerce-cart' => 'ecommerce-cart',
        'icon-ecommerce-cart-check' => 'ecommerce-cart-check',
        'icon-ecommerce-cart-cloud' => 'ecommerce-cart-cloud',
        'icon-ecommerce-cart-content' => 'ecommerce-cart-content',
        'icon-ecommerce-cart-download' => 'ecommerce-cart-download',
        'icon-ecommerce-cart-minus' => 'ecommerce-cart-minus',
        'icon-ecommerce-cart-plus' => 'ecommerce-cart-plus',
        'icon-ecommerce-cart-refresh' => 'ecommerce-cart-refresh',
        'icon-ecommerce-cart-remove' => 'ecommerce-cart-remove',
        'icon-ecommerce-cart-search' => 'ecommerce-cart-search',
        'icon-ecommerce-cart-upload' => 'ecommerce-cart-upload',
        'icon-ecommerce-cent' => 'ecommerce-cent',
        'icon-ecommerce-colon' => 'ecommerce-colon',
        'icon-ecommerce-creditcard' => 'ecommerce-creditcard',
        'icon-ecommerce-diamond' => 'ecommerce-diamond',
        'icon-ecommerce-dollar' => 'ecommerce-dollar',
        'icon-ecommerce-euro' => 'ecommerce-euro',
        'icon-ecommerce-franc' => 'ecommerce-franc',
        'icon-ecommerce-gift' => 'ecommerce-gift',
        'icon-ecommerce-graph1' => 'icon-ecommerce-graph1',
        'icon-ecommerce-graph2' => 'icon-ecommerce-graph2',
        'icon-ecommerce-graph3' => 'icon-ecommerce-graph3',
        'icon-ecommerce-graph-decrease' => 'ecommerce-graph-decrease',
        'icon-ecommerce-graph-increase' => 'ecommerce-graph-increase',
        'icon-ecommerce-guarani' => 'ecommerce-guarani',
        'icon-ecommerce-kips' => 'ecommerce-kips',
        'icon-ecommerce-lira' => 'ecommerce-lira',
        'icon-ecommerce-megaphone' => 'ecommerce-megaphone',
        'icon-ecommerce-money' => 'ecommerce-money',
        'icon-ecommerce-naira' => 'ecommerce-naira',
        'icon-ecommerce-pesos' => 'ecommerce-pesos',
        'icon-ecommerce-pound' => 'ecommerce-pound',
        'icon-ecommerce-receipt' => 'ecommerce-receipt',
        'icon-ecommerce-receipt-bath' => 'ecommerce-receipt-bath',
        'icon-ecommerce-receipt-cent' => 'ecommerce-receipt-cent',
        'icon-ecommerce-receipt-dollar' => 'ecommerce-receipt-dollar',
        'icon-ecommerce-receipt-euro' => 'ecommerce-receipt-euro',
        'icon-ecommerce-receipt-franc' => 'ecommerce-receipt-franc',
        'icon-ecommerce-receipt-guarani' => 'ecommerce-receipt-guarani',
        'icon-ecommerce-receipt-kips' => 'ecommerce-receipt-kips',
        'icon-ecommerce-receipt-lira' => 'ecommerce-receipt-lira',
        'icon-ecommerce-receipt-naira' => 'ecommerce-receipt-naira',
        'icon-ecommerce-receipt-pesos' => 'ecommerce-receipt-pesos',
        'icon-ecommerce-receipt-pound' => 'ecommerce-receipt-pound',
        'icon-ecommerce-receipt-rublo' => 'ecommerce-receipt-rublo',
        'icon-ecommerce-receipt-rupee' => 'ecommerce-receipt-rupee',
        'icon-ecommerce-receipt-tugrik' => 'ecommerce-receipt-tugrik',
        'icon-ecommerce-receipt-won' => 'ecommerce-receipt-won',
        'icon-ecommerce-receipt-yen' => 'ecommerce-receipt-yen',
        'icon-ecommerce-receipt-yen2' => 'ecommerce-receipt-yen2',
        'icon-ecommerce-recept-colon' => 'ecommerce-recept-colon',
        'icon-ecommerce-rublo' => 'ecommerce-rublo',
        'icon-ecommerce-rupee' => 'ecommerce-rupee',
        'icon-ecommerce-safe' => 'ecommerce-safe',
        'icon-ecommerce-sale' => 'ecommerce-sale',
        'icon-ecommerce-sales' => 'ecommerce-sales',
        'icon-ecommerce-ticket' => 'ecommerce-ticket',
        'icon-ecommerce-tugriks' => 'ecommerce-tugriks',
        'icon-ecommerce-wallet' => 'ecommerce-wallet',
        'icon-ecommerce-won' => 'ecommerce-won',
        'icon-ecommerce-yen' => 'ecommerce-yen',
        'icon-ecommerce-yen2' => 'icon-ecommerce-yen2',
        /* Linea Music */
        'icon-music-beginning-button' => 'music-beginning-button',
        'icon-music-bell' => 'music-bell',
        'icon-music-cd' => 'music-cd',
        'icon-music-diapason' => 'music-diapason',
        'icon-music-eject-button' => 'music-eject-button',
        'icon-music-end-button' => 'music-end-button',
        'icon-music-fastforward-button' => 'music-fastforward-button',
        'icon-music-headphones' => 'music-headphones',
        'icon-music-ipod' => 'music-ipod',
        'icon-music-loudspeaker' => 'music-loudspeaker',
        'icon-music-microphone' => 'music-microphone',
        'icon-music-microphone-old' => 'music-microphone-old',
        'icon-music-mixer' => 'music-mixer',
        'icon-music-mute' => 'music-mute',
        'icon-music-note-multiple' => 'music-note-multiple',
        'icon-music-note-single' => 'music-note-single',
        'icon-music-pause-button' => 'music-pause-button',
        'icon-music-play-button' => 'music-play-button',
        'icon-music-playlist' => 'music-playlist',
        'icon-music-radio-ghettoblaster' => 'music-radio-ghettoblaster',
        'icon-music-radio-portable' => 'music-radio-portable',
        'icon-music-record' => 'music-record',
        'icon-music-recordplayer' => 'music-recordplayer',
        'icon-music-repeat-button' => 'music-repeat-button',
        'icon-music-rewind-button' => 'music-rewind-button',
        'icon-music-shuffle-button' => 'music-shuffle-button',
        'icon-music-stop-button' => 'music-stop-button',
        'icon-music-tape' => 'music-tape',
        'icon-music-volume-down' => 'music-volume-down',
        'icon-music-volume-up' => 'music-volume-up',
        /* Linea Software */
        'icon-software-add-vectorpoint' => 'software-add-vectorpoint',
        'icon-software-box-oval' => 'software-box-oval',
        'icon-software-box-polygon' => 'software-box-polygon',
        'icon-software-box-rectangle' => 'software-box-rectangle',
        'icon-software-box-roundedrectangle' => 'software-box-roundedrectangle',
        'icon-software-character' => 'software-character',
        'icon-software-crop' => 'software-crop',
        'icon-software-eyedropper' => 'software-eyedropper',
        'icon-software-font-allcaps' => 'software-font-allcaps',
        'icon-software-font-baseline-shift' => 'software-font-baseline-shift',
        'icon-software-font-horizontal-scale' => 'software-font-horizontal-scale',
        'icon-software-font-kerning' => 'software-font-kerning',
        'icon-software-font-leading' => 'software-font-leading',
        'icon-software-font-size' => 'software-font-size',
        'icon-software-font-smallcapital' => 'software-font-smallcapital',
        'icon-software-font-smallcaps' => 'software-font-smallcaps',
        'icon-software-font-strikethrough' => 'software-font-strikethrough',
        'icon-software-font-tracking' => 'software-font-tracking',
        'icon-software-font-underline' => 'software-font-underline',
        'icon-software-font-vertical-scale' => 'software-font-vertical-scale',
        'icon-software-horizontal-align-center' => 'software-horizontal-align-center',
        'icon-software-horizontal-align-left' => 'software-horizontal-align-left',
        'icon-software-horizontal-align-right' => 'software-horizontal-align-right',
        'icon-software-horizontal-distribute-center' => 'software-horizontal-distribute-center',
        'icon-software-horizontal-distribute-left' => 'software-horizontal-distribute-left',
        'icon-software-horizontal-distribute-right' => 'software-horizontal-distribute-right',
        'icon-software-indent-firstline' => 'software-indent-firstline',
        'icon-software-indent-left' => 'software-indent-left',
        'icon-software-indent-right' => 'software-indent-right',
        'icon-software-lasso' => 'software-lasso',
        'icon-software-layers1' => 'icon-software-layers1',
        'icon-software-layers2' => 'icon-software-layers2',
        'icon-software-layout' => 'software-layout',
        'icon-software-layout-2columns' => 'software-layout-2columns',
        'icon-software-layout-3columns' => 'software-layout-3columns',
        'icon-software-layout-4boxes' => 'software-layout-4boxes',
        'icon-software-layout-4columns' => 'software-layout-4columns',
        'icon-software-layout-4lines' => 'software-layout-4lines',
        'icon-software-layout-8boxes' => 'software-layout-8boxes',
        'icon-software-layout-header' => 'software-layout-header',
        'icon-software-layout-header-2columns' => 'software-layout-header-2columns',
        'icon-software-layout-header-3columns' => 'software-layout-header-3columns',
        'icon-software-layout-header-4boxes' => 'software-layout-header-4boxes',
        'icon-software-layout-header-4columns' => 'software-layout-header-4columns',
        'icon-software-layout-header-complex' => 'software-layout-header-complex',
        'icon-software-layout-header-complex2' => 'software-layout-header-complex2',
        'icon-software-layout-header-complex3' => 'software-layout-header-complex3',
        'icon-software-layout-header-complex4' => 'software-layout-header-complex4',
        'icon-software-layout-header-sideleft' => 'software-layout-header-sideleft',
        'icon-software-layout-header-sideright' => 'software-layout-header-sideright',
        'icon-software-layout-sidebar-left' => 'software-layout-sidebar-left',
        'icon-software-layout-sidebar-right' => 'software-layout-sidebar-right',
        'icon-software-magnete' => 'software-magnete',
        'icon-software-pages' => 'software-pages',
        'icon-software-paintbrush' => 'software-paintbrush',
        'icon-software-paintbucket' => 'software-paintbucket',
        'icon-software-paintroller' => 'software-paintroller',
        'icon-software-paragraph' => 'software-paragraph',
        'icon-software-paragraph-align-left' => 'software-paragraph-align-left',
        'icon-software-paragraph-align-right' => 'software-paragraph-align-right',
        'icon-software-paragraph-center' => 'software-paragraph-center',
        'icon-software-paragraph-justify-all' => 'software-paragraph-justify-all',
        'icon-software-paragraph-justify-center' => 'software-paragraph-justify-center',
        'icon-software-paragraph-justify-left' => 'software-paragraph-justify-left',
        'icon-software-paragraph-justify-right' => 'software-paragraph-justify-right',
        'icon-software-paragraph-space-after' => 'software-paragraph-space-after',
        'icon-software-paragraph-space-before' => 'software-paragraph-space-before',
        'icon-software-pathfinder-exclude' => 'software-pathfinder-exclude',
        'icon-software-pathfinder-intersect' => 'software-pathfinder-intersect',
        'icon-software-pathfinder-subtract' => 'software-pathfinder-subtract',
        'icon-software-pathfinder-unite' => 'software-pathfinder-unite',
        'icon-software-pen' => 'software-pen',
        'icon-software-pen-add' => 'software-pen-add',
        'icon-software-pen-remove' => 'software-pen-remove',
        'icon-software-pencil' => 'software-pencil',
        'icon-software-polygonallasso' => 'software-polygonallasso',
        'icon-software-reflect-horizontal' => 'software-reflect-horizontal',
        'icon-software-reflect-vertical' => 'software-reflect-vertical',
        'icon-software-remove-vectorpoint' => 'software-remove-vectorpoint',
        'icon-software-scale-expand' => 'software-scale-expand',
        'icon-software-scale-reduce' => 'software-scale-reduce',
        'icon-software-selection-oval' => 'software-selection-oval',
        'icon-software-selection-polygon' => 'software-selection-polygon',
        'icon-software-selection-rectangle' => 'software-selection-rectangle',
        'icon-software-selection-roundedrectangle' => 'software-selection-roundedrectangle',
        'icon-software-shape-oval' => 'software-shape-oval',
        'icon-software-shape-polygon' => 'software-shape-polygon',
        'icon-software-shape-rectangle' => 'software-shape-rectangle',
        'icon-software-shape-roundedrectangle' => 'software-shape-roundedrectangle',
        'icon-software-slice' => 'software-slice',
        'icon-software-transform-bezier' => 'software-transform-bezier',
        'icon-software-vector-box' => 'software-vector-box',
        'icon-software-vector-composite' => 'software-vector-composite',
        'icon-software-vector-line' => 'software-vector-line',
        'icon-software-vertical-align-bottom' => 'software-vertical-align-bottom',
        'icon-software-vertical-align-center' => 'software-vertical-align-center',
        'icon-software-vertical-align-top' => 'software-vertical-align-top',
        'icon-software-vertical-distribute-bottom' => 'software-vertical-distribute-bottom',
        'icon-software-vertical-distribute-center' => 'software-vertical-distribute-center',
        'icon-software-vertical-distribute-top' => 'software-vertical-distribute-top',
        /* Linea Weather */
        'icon-weather-aquarius' => 'weather-aquarius',
        'icon-weather-aries' => 'weather-aries',
        'icon-weather-cancer' => 'weather-cancer',
        'icon-weather-capricorn' => 'weather-capricorn',
        'icon-weather-cloud' => 'weather-cloud',
        'icon-weather-cloud-drop' => 'weather-cloud-drop',
        'icon-weather-cloud-lightning' => 'weather-cloud-lightning',
        'icon-weather-cloud-snowflake' => 'weather-cloud-snowflake',
        'icon-weather-downpour-fullmoon' => 'weather-downpour-fullmoon',
        'icon-weather-downpour-halfmoon' => 'weather-downpour-halfmoon',
        'icon-weather-downpour-sun' => 'weather-downpour-sun',
        'icon-weather-drop' => 'weather-drop',
        'icon-weather-first-quarter' => 'weather-first-quarter',
        'icon-weather-fog' => 'weather-fog',
        'icon-weather-fog-fullmoon' => 'weather-fog-fullmoon',
        'icon-weather-fog-halfmoon' => 'weather-fog-halfmoon',
        'icon-weather-fog-sun' => 'weather-fog-sun',
        'icon-weather-fullmoon' => 'weather-fullmoon',
        'icon-weather-gemini' => 'weather-gemini',
        'icon-weather-hail' => 'weather-hail',
        'icon-weather-hail-fullmoon' => 'weather-hail-fullmoon',
        'icon-weather-hail-halfmoon' => 'weather-hail-halfmoon',
        'icon-weather-hail-sun' => 'weather-hail-sun',
        'icon-weather-last-quarter' => 'weather-last-quarter',
        'icon-weather-leo' => 'weather-leo',
        'icon-weather-libra' => 'weather-libra',
        'icon-weather-lightning' => 'weather-lightning',
        'icon-weather-mistyrain' => 'weather-mistyrain',
        'icon-weather-mistyrain-fullmoon' => 'weather-mistyrain-fullmoon',
        'icon-weather-mistyrain-halfmoon' => 'weather-mistyrain-halfmoon',
        'icon-weather-mistyrain-sun' => 'weather-mistyrain-sun',
        'icon-weather-moon' => 'weather-moon',
        'icon-weather-moondown-full' => 'weather-moondown-full',
        'icon-weather-moondown-half' => 'weather-moondown-half',
        'icon-weather-moonset-full' => 'weather-moonset-full',
        'icon-weather-moonset-half' => 'weather-moonset-half',
        'icon-weather-move2' => 'icon-weather-move2',
        'icon-weather-newmoon' => 'weather-newmoon',
        'icon-weather-pisces' => 'weather-pisces',
        'icon-weather-rain' => 'weather-rain',
        'icon-weather-rain-fullmoon' => 'weather-rain-fullmoon',
        'icon-weather-rain-halfmoon' => 'weather-rain-halfmoon',
        'icon-weather-rain-sun' => 'weather-rain-sun',
        'icon-weather-sagittarius' => 'weather-sagittarius',
        'icon-weather-scorpio' => 'weather-scorpio',
        'icon-weather-snow' => 'weather-snow',
        'icon-weather-snow-fullmoon' => 'weather-snow-fullmoon',
        'icon-weather-snow-halfmoon' => 'weather-snow-halfmoon',
        'icon-weather-snow-sun' => 'weather-snow-sun',
        'icon-weather-snowflake' => 'weather-snowflake',
        'icon-weather-star' => 'weather-star',
        'icon-weather-storm-11' => 'weather-storm-11',
        'icon-weather-storm-32' => 'weather-storm-32',
        'icon-weather-storm-fullmoon' => 'weather-storm-fullmoon',
        'icon-weather-storm-halfmoon' => 'weather-storm-halfmoon',
        'icon-weather-storm-sun' => 'weather-storm-sun',
        'icon-weather-sun' => 'weather-sun',
        'icon-weather-sundown' => 'weather-sundown',
        'icon-weather-sunset' => 'weather-sunset',
        'icon-weather-taurus' => 'weather-taurus',
        'icon-weather-tempest' => 'weather-tempest',
        'icon-weather-tempest-fullmoon' => 'weather-tempest-fullmoon',
        'icon-weather-tempest-halfmoon' => 'weather-tempest-halfmoon',
        'icon-weather-tempest-sun' => 'weather-tempest-sun',
        'icon-weather-variable-fullmoon' => 'weather-variable-fullmoon',
        'icon-weather-variable-halfmoon' => 'weather-variable-halfmoon',
        'icon-weather-variable-sun' => 'weather-variable-sun',
        'icon-weather-virgo' => 'weather-virgo',
        'icon-weather-waning-cresent' => 'weather-waning-cresent',
        'icon-weather-waning-gibbous' => 'weather-waning-gibbous',
        'icon-weather-waxing-cresent' => 'weather-waxing-cresent',
        'icon-weather-waxing-gibbous' => 'weather-waxing-gibbous',
        'icon-weather-wind' => 'weather-wind',
        'icon-weather-wind-e' => 'weather-wind-e',
        'icon-weather-wind-fullmoon' => 'weather-wind-fullmoon',
        'icon-weather-wind-halfmoon' => 'weather-wind-halfmoon',
        'icon-weather-wind-n' => 'weather-wind-n',
        'icon-weather-wind-ne' => 'weather-wind-ne',
        'icon-weather-wind-nw' => 'weather-wind-nw',
        'icon-weather-wind-s' => 'weather-wind-s',
        'icon-weather-wind-se' => 'weather-wind-se',
        'icon-weather-wind-sun' => 'weather-wind-sun',
        'icon-weather-wind-sw' => 'weather-wind-sw',
        'icon-weather-wind-w' => 'weather-wind-w',
        'icon-weather-windgust' => 'weather-windgust',
    ];
}

function themo_fa_icons() {
    return [
        // Travel Pack
        'th-trip travelpack-aqualung-bottles',
        'th-trip travelpack-baseball-headgear',
        'th-trip travelpack-beach-bag',
        'th-trip travelpack-beach-ball',
        'th-trip travelpack-beach-mattress',
        'th-trip travelpack-big-trip-caravan',
        'th-trip travelpack-binoculars',
        'th-trip travelpack-boat-anchor',
        'th-trip travelpack-cableway-lift',
        'th-trip travelpack-cadillac-car',
        'th-trip travelpack-camel-walking',
        'th-trip travelpack-camping-tent',
        'th-trip travelpack-car-trip',
        'th-trip travelpack-carnival-masks',
        'th-trip travelpack-circular-watch',
        'th-trip travelpack-concert-tickets',
        'th-trip travelpack-construction-jacket',
        'th-trip travelpack-cruise-liner-boat',
        'th-trip travelpack-digital-photography-camera',
        'th-trip travelpack-direction-sign',
        'th-trip travelpack-double-dice',
        'th-trip travelpack-dubai-burj-al-arab',
        'th-trip travelpack-extensible-pirate-spyglass',
        'th-trip travelpack-female-swim-suit',
        'th-trip travelpack-film-roll',
        'th-trip travelpack-flip-flops-top-view',
        'th-trip travelpack-flippers',
        'th-trip travelpack-flying-helicopter',
        'th-trip travelpack-flying-kite',
        'th-trip travelpack-fork-plate-knife',
        'th-trip travelpack-french-eiffel-tower',
        'th-trip travelpack-frontal-reflex-camera',
        'th-trip travelpack-frontal-school-bus',
        'th-trip travelpack-frontal-train',
        'th-trip travelpack-frontal-video-camera',
        'th-trip travelpack-gym-dumbbell',
        'th-trip travelpack-hand-fan',
        'th-trip travelpack-hanger-with-towel',
        'th-trip travelpack-high-speed-train',
        'th-trip travelpack-hot-air-baloon-flying',
        'th-trip travelpack-hotel-key',
        'th-trip travelpack-indian-tent',
        'th-trip travelpack-inflatable-boat-top-view',
        'th-trip travelpack-jellyfish',
        'th-trip travelpack-journey-bag',
        'th-trip travelpack-kayak-top-view',
        'th-trip travelpack-king-size-bed',
        'th-trip travelpack-lifebuoy',
        'th-trip travelpack-luggage-cart',
        'th-trip travelpack-map-pin',
        'th-trip travelpack-martini-glass',
        'th-trip travelpack-mosque-construction',
        'th-trip travelpack-motorbiking-trip',
        'th-trip travelpack-motorcycle-helmet',
        'th-trip travelpack-mountains-with-snow',
        'th-trip travelpack-movie-photogram',
        'th-trip travelpack-open-umbrella',
        'th-trip travelpack-orientation-compass',
        'th-trip travelpack-party-drink',
        'th-trip travelpack-passports',
        'th-trip travelpack-petrol-station',
        'th-trip travelpack-ping-pong-rackets',
        'th-trip travelpack-pisa-tower',
        'th-trip travelpack-polaroid-pictures',
        'th-trip travelpack-postal-stamp',
        'th-trip travelpack-pyramids-of-egypt',
        'th-trip travelpack-reading-glasses',
        'th-trip travelpack-reception-bell',
        'th-trip travelpack-retro-bicycle',
        'th-trip travelpack-room-service',
        'th-trip travelpack-safety-box',
        'th-trip travelpack-sailing-yacht',
        'th-trip travelpack-scooter',
        'th-trip travelpack-scuba-mask',
        'th-trip travelpack-sea-horse',
        'th-trip travelpack-sea-shell',
        'th-trip travelpack-ship-steering-wheel',
        'th-trip travelpack-shower-head-running-water',
        'th-trip travelpack-skis-and-sticks',
        'th-trip travelpack-snowboard-with-boot',
        'th-trip travelpack-snowmobile',
        'th-trip travelpack-starfish',
        'th-trip travelpack-suitcase-with-wheels',
        'th-trip travelpack-suitcase-with-wheels-1',
        'th-trip travelpack-summer-sun',
        'th-trip travelpack-sunbed',
        'th-trip travelpack-surf-board',
        'th-trip travelpack-swimming-trunks',
        'th-trip travelpack-taxi-sign',
        'th-trip travelpack-tennis-equipment',
        'th-trip travelpack-travelling-backpack',
        'th-trip travelpack-trifolded-map-route',
        'th-trip travelpack-trip-bag',
        'th-trip travelpack-tropical-fish',
        'th-trip travelpack-two-credit-cards',
        'th-trip travelpack-two-palm-trees-island',
        'th-trip travelpack-women-hat',
        'th-trip travelpack-world-wide-web',
        /* Linea Arrows */
        'icon-arrows-anticlockwise',
        'icon-arrows-anticlockwise-dashed',
        'icon-arrows-button-down',
        'icon-arrows-button-off',
        'icon-arrows-button-on',
        'icon-arrows-button-up',
        'icon-arrows-check',
        'icon-arrows-circle-check',
        'icon-arrows-circle-down',
        'icon-arrows-circle-downleft',
        'icon-arrows-circle-downright',
        'icon-arrows-circle-left',
        'icon-arrows-circle-minus',
        'icon-arrows-circle-plus',
        'icon-arrows-circle-remove',
        'icon-arrows-circle-right',
        'icon-arrows-circle-up',
        'icon-arrows-circle-upleft',
        'icon-arrows-circle-upright',
        'icon-arrows-clockwise',
        'icon-arrows-clockwise-dashed',
        'icon-arrows-compress',
        'icon-arrows-deny',
        'icon-arrows-diagonal',
        'icon-arrows-diagonal2',
        'icon-arrows-down',
        'icon-arrows-down-double',
        'icon-arrows-downleft',
        'icon-arrows-downright',
        'icon-arrows-drag-down',
        'icon-arrows-drag-down-dashed',
        'icon-arrows-drag-horiz',
        'icon-arrows-drag-left',
        'icon-arrows-drag-left-dashed',
        'icon-arrows-drag-right',
        'icon-arrows-drag-right-dashed',
        'icon-arrows-drag-up',
        'icon-arrows-drag-up-dashed',
        'icon-arrows-drag-vert',
        'icon-arrows-exclamation',
        'icon-arrows-expand',
        'icon-arrows-expand-diagonal1',
        'icon-arrows-expand-horizontal1',
        'icon-arrows-expand-vertical1',
        'icon-arrows-fit-horizontal',
        'icon-arrows-fit-vertical',
        'icon-arrows-glide',
        'icon-arrows-glide-horizontal',
        'icon-arrows-glide-vertical',
        'icon-arrows-hamburger1',
        'icon-arrows-hamburger-2',
        'icon-arrows-horizontal',
        'icon-arrows-info',
        'icon-arrows-keyboard-alt',
        'icon-arrows-keyboard-cmd',
        'icon-arrows-keyboard-delete',
        'icon-arrows-keyboard-down',
        'icon-arrows-keyboard-left',
        'icon-arrows-keyboard-return',
        'icon-arrows-keyboard-right',
        'icon-arrows-keyboard-shift',
        'icon-arrows-keyboard-tab',
        'icon-arrows-keyboard-up',
        'icon-arrows-left',
        'icon-arrows-left-double-32',
        'icon-arrows-minus',
        'icon-arrows-move',
        'icon-arrows-move2',
        'icon-arrows-move-bottom',
        'icon-arrows-move-left',
        'icon-arrows-move-right',
        'icon-arrows-move-top',
        'icon-arrows-plus',
        'icon-arrows-question',
        'icon-arrows-remove',
        'icon-arrows-right',
        'icon-arrows-right-double',
        'icon-arrows-rotate',
        'icon-arrows-rotate-anti',
        'icon-arrows-rotate-anti-dashed',
        'icon-arrows-rotate-dashed',
        'icon-arrows-shrink',
        'icon-arrows-shrink-diagonal1',
        'icon-arrows-shrink-diagonal2',
        'icon-arrows-shrink-horizonal2',
        'icon-arrows-shrink-horizontal1',
        'icon-arrows-shrink-vertical1',
        'icon-arrows-shrink-vertical2',
        'icon-arrows-sign-down',
        'icon-arrows-sign-left',
        'icon-arrows-sign-right',
        'icon-arrows-sign-up',
        'icon-arrows-slide-down1',
        'icon-arrows-slide-down2',
        'icon-arrows-slide-left1',
        'icon-arrows-slide-left2',
        'icon-arrows-slide-right1',
        'icon-arrows-slide-right2',
        'icon-arrows-slide-up1',
        'icon-arrows-slide-up2',
        'icon-arrows-slim-down',
        'icon-arrows-slim-down-dashed',
        'icon-arrows-slim-left',
        'icon-arrows-slim-left-dashed',
        'icon-arrows-slim-right',
        'icon-arrows-slim-right-dashed',
        'icon-arrows-slim-up',
        'icon-arrows-slim-up-dashed',
        'icon-arrows-square-check',
        'icon-arrows-square-down',
        'icon-arrows-square-downleft',
        'icon-arrows-square-downright',
        'icon-arrows-square-left',
        'icon-arrows-square-minus',
        'icon-arrows-square-plus',
        'icon-arrows-square-remove',
        'icon-arrows-square-right',
        'icon-arrows-square-up',
        'icon-arrows-square-upleft',
        'icon-arrows-square-upright',
        'icon-arrows-squares',
        'icon-arrows-stretch-diagonal1',
        'icon-arrows-stretch-diagonal2',
        'icon-arrows-stretch-diagonal3',
        'icon-arrows-stretch-diagonal4',
        'icon-arrows-stretch-horizontal1',
        'icon-arrows-stretch-horizontal2',
        'icon-arrows-stretch-vertical1',
        'icon-arrows-stretch-vertical2',
        'icon-arrows-switch-horizontal',
        'icon-arrows-switch-vertical',
        'icon-arrows-up',
        'icon-arrows-up-double-33',
        'icon-arrows-upleft',
        'icon-arrows-upright',
        'icon-arrows-vertical',
        /* Linea Basic */
        'icon-basic-accelerator',
        'icon-basic-alarm',
        'icon-basic-anchor',
        'icon-basic-anticlockwise',
        'icon-basic-archive',
        'icon-basic-archive-full',
        'icon-basic-ban',
        'icon-basic-battery-charge',
        'icon-basic-battery-empty',
        'icon-basic-battery-full',
        'icon-basic-battery-half',
        'icon-basic-bolt',
        'icon-basic-book',
        'icon-basic-book-pen',
        'icon-basic-book-pencil',
        'icon-basic-bookmark',
        'icon-basic-calculator',
        'icon-basic-calendar',
        'icon-basic-cards-diamonds',
        'icon-basic-cards-hearts',
        'icon-basic-case',
        'icon-basic-chronometer',
        'icon-basic-clessidre',
        'icon-basic-clock',
        'icon-basic-clockwise',
        'icon-basic-cloud',
        'icon-basic-clubs',
        'icon-basic-compass',
        'icon-basic-cup',
        'icon-basic-diamonds',
        'icon-basic-display',
        'icon-basic-download',
        'icon-basic-exclamation',
        'icon-basic-eye',
        'icon-basic-eye-closed',
        'icon-basic-female',
        'icon-basic-flag1',
        'icon-basic-flag2',
        'icon-basic-floppydisk',
        'icon-basic-folder',
        'icon-basic-folder-multiple',
        'icon-basic-gear',
        'icon-basic-geolocalize-01',
        'icon-basic-geolocalize-05',
        'icon-basic-globe',
        'icon-basic-gunsight',
        'icon-basic-hammer',
        'icon-basic-headset',
        'icon-basic-heart',
        'icon-basic-heart-broken',
        'icon-basic-helm',
        'icon-basic-home',
        'icon-basic-info',
        'icon-basic-ipod',
        'icon-basic-joypad',
        'icon-basic-key',
        'icon-basic-keyboard',
        'icon-basic-laptop',
        'icon-basic-life-buoy',
        'icon-basic-lightbulb',
        'icon-basic-link',
        'icon-basic-lock',
        'icon-basic-lock-open',
        'icon-basic-magic-mouse',
        'icon-basic-magnifier',
        'icon-basic-magnifier-minus',
        'icon-basic-magnifier-plus',
        'icon-basic-mail',
        'icon-basic-mail-multiple',
        'icon-basic-mail-open',
        'icon-basic-mail-open-text',
        'icon-basic-male',
        'icon-basic-map',
        'icon-basic-message',
        'icon-basic-message-multiple',
        'icon-basic-message-txt',
        'icon-basic-mixer2',
        'icon-basic-mouse',
        'icon-basic-notebook',
        'icon-basic-notebook-pen',
        'icon-basic-notebook-pencil',
        'icon-basic-paperplane',
        'icon-basic-pencil-ruler',
        'icon-basic-pencil-ruler-pen',
        'icon-basic-photo',
        'icon-basic-picture',
        'icon-basic-picture-multiple',
        'icon-basic-pin1',
        'icon-basic-pin2',
        'icon-basic-postcard',
        'icon-basic-postcard-multiple',
        'icon-basic-printer',
        'icon-basic-question',
        'icon-basic-rss',
        'icon-basic-server',
        'icon-basic-server2',
        'icon-basic-server-cloud',
        'icon-basic-server-download',
        'icon-basic-server-upload',
        'icon-basic-settings',
        'icon-basic-share',
        'icon-basic-sheet',
        'icon-basic-sheet-multiple',
        'icon-basic-sheet-pen',
        'icon-basic-sheet-pencil',
        'icon-basic-sheet-txt',
        'icon-basic-signs',
        'icon-basic-smartphone',
        'icon-basic-spades',
        'icon-basic-spread',
        'icon-basic-spread-bookmark',
        'icon-basic-spread-text',
        'icon-basic-spread-text-bookmark',
        'icon-basic-star',
        'icon-basic-tablet',
        'icon-basic-target',
        'icon-basic-todo',
        'icon-basic-todo-pen',
        'icon-basic-todo-pencil',
        'icon-basic-todo-txt',
        'icon-basic-todolist-pen',
        'icon-basic-todolist-pencil',
        'icon-basic-trashcan',
        'icon-basic-trashcan-full',
        'icon-basic-trashcan-refresh',
        'icon-basic-trashcan-remove',
        'icon-basic-upload',
        'icon-basic-usb',
        'icon-basic-video',
        'icon-basic-watch',
        'icon-basic-webpage',
        'icon-basic-webpage-img-txt',
        'icon-basic-webpage-multiple',
        'icon-basic-webpage-txt',
        'icon-basic-world',
        /* Linea Basic Elaboration */
        'icon-basic-elaboration-bookmark-check',
        'icon-basic-elaboration-bookmark-minus',
        'icon-basic-elaboration-bookmark-plus',
        'icon-basic-elaboration-bookmark-remove',
        'icon-basic-elaboration-briefcase-check',
        'icon-basic-elaboration-briefcase-download',
        'icon-basic-elaboration-briefcase-flagged',
        'icon-basic-elaboration-briefcase-minus',
        'icon-basic-elaboration-briefcase-plus',
        'icon-basic-elaboration-briefcase-refresh',
        'icon-basic-elaboration-briefcase-remove',
        'icon-basic-elaboration-briefcase-search',
        'icon-basic-elaboration-briefcase-star',
        'icon-basic-elaboration-briefcase-upload',
        'icon-basic-elaboration-browser-check',
        'icon-basic-elaboration-browser-download',
        'icon-basic-elaboration-browser-minus',
        'icon-basic-elaboration-browser-plus',
        'icon-basic-elaboration-browser-refresh',
        'icon-basic-elaboration-browser-remove',
        'icon-basic-elaboration-browser-search',
        'icon-basic-elaboration-browser-star',
        'icon-basic-elaboration-browser-upload',
        'icon-basic-elaboration-calendar-check',
        'icon-basic-elaboration-calendar-cloud',
        'icon-basic-elaboration-calendar-download',
        'icon-basic-elaboration-calendar-empty',
        'icon-basic-elaboration-calendar-flagged',
        'icon-basic-elaboration-calendar-heart',
        'icon-basic-elaboration-calendar-minus',
        'icon-basic-elaboration-calendar-next',
        'icon-basic-elaboration-calendar-noaccess',
        'icon-basic-elaboration-calendar-pencil',
        'icon-basic-elaboration-calendar-plus',
        'icon-basic-elaboration-calendar-previous',
        'icon-basic-elaboration-calendar-refresh',
        'icon-basic-elaboration-calendar-remove',
        'icon-basic-elaboration-calendar-search',
        'icon-basic-elaboration-calendar-star',
        'icon-basic-elaboration-calendar-upload',
        'icon-basic-elaboration-cloud-check',
        'icon-basic-elaboration-cloud-download',
        'icon-basic-elaboration-cloud-minus',
        'icon-basic-elaboration-cloud-noaccess',
        'icon-basic-elaboration-cloud-plus',
        'icon-basic-elaboration-cloud-refresh',
        'icon-basic-elaboration-cloud-remove',
        'icon-basic-elaboration-cloud-search',
        'icon-basic-elaboration-cloud-upload',
        'icon-basic-elaboration-document-check',
        'icon-basic-elaboration-document-cloud',
        'icon-basic-elaboration-document-download',
        'icon-basic-elaboration-document-flagged',
        'icon-basic-elaboration-document-graph',
        'icon-basic-elaboration-document-heart',
        'icon-basic-elaboration-document-minus',
        'icon-basic-elaboration-document-next',
        'icon-basic-elaboration-document-noaccess',
        'icon-basic-elaboration-document-note',
        'icon-basic-elaboration-document-pencil',
        'icon-basic-elaboration-document-picture',
        'icon-basic-elaboration-document-plus',
        'icon-basic-elaboration-document-previous',
        'icon-basic-elaboration-document-refresh',
        'icon-basic-elaboration-document-remove',
        'icon-basic-elaboration-document-search',
        'icon-basic-elaboration-document-star',
        'icon-basic-elaboration-document-upload',
        'icon-basic-elaboration-folder-check',
        'icon-basic-elaboration-folder-cloud',
        'icon-basic-elaboration-folder-document',
        'icon-basic-elaboration-folder-download',
        'icon-basic-elaboration-folder-flagged',
        'icon-basic-elaboration-folder-graph',
        'icon-basic-elaboration-folder-heart',
        'icon-basic-elaboration-folder-minus',
        'icon-basic-elaboration-folder-next',
        'icon-basic-elaboration-folder-noaccess',
        'icon-basic-elaboration-folder-note',
        'icon-basic-elaboration-folder-pencil',
        'icon-basic-elaboration-folder-picture',
        'icon-basic-elaboration-folder-plus',
        'icon-basic-elaboration-folder-previous',
        'icon-basic-elaboration-folder-refresh',
        'icon-basic-elaboration-folder-remove',
        'icon-basic-elaboration-folder-search',
        'icon-basic-elaboration-folder-star',
        'icon-basic-elaboration-folder-upload',
        'icon-basic-elaboration-mail-check',
        'icon-basic-elaboration-mail-cloud',
        'icon-basic-elaboration-mail-document',
        'icon-basic-elaboration-mail-download',
        'icon-basic-elaboration-mail-flagged',
        'icon-basic-elaboration-mail-heart',
        'icon-basic-elaboration-mail-next',
        'icon-basic-elaboration-mail-noaccess',
        'icon-basic-elaboration-mail-note',
        'icon-basic-elaboration-mail-pencil',
        'icon-basic-elaboration-mail-picture',
        'icon-basic-elaboration-mail-previous',
        'icon-basic-elaboration-mail-refresh',
        'icon-basic-elaboration-mail-remove',
        'icon-basic-elaboration-mail-search',
        'icon-basic-elaboration-mail-star',
        'icon-basic-elaboration-mail-upload',
        'icon-basic-elaboration-message-check',
        'icon-basic-elaboration-message-dots',
        'icon-basic-elaboration-message-happy',
        'icon-basic-elaboration-message-heart',
        'icon-basic-elaboration-message-minus',
        'icon-basic-elaboration-message-note',
        'icon-basic-elaboration-message-plus',
        'icon-basic-elaboration-message-refresh',
        'icon-basic-elaboration-message-remove',
        'icon-basic-elaboration-message-sad',
        'icon-basic-elaboration-smartphone-cloud',
        'icon-basic-elaboration-smartphone-heart',
        'icon-basic-elaboration-smartphone-noaccess',
        'icon-basic-elaboration-smartphone-note',
        'icon-basic-elaboration-smartphone-pencil',
        'icon-basic-elaboration-smartphone-picture',
        'icon-basic-elaboration-smartphone-refresh',
        'icon-basic-elaboration-smartphone-search',
        'icon-basic-elaboration-tablet-cloud',
        'icon-basic-elaboration-tablet-heart',
        'icon-basic-elaboration-tablet-noaccess',
        'icon-basic-elaboration-tablet-note',
        'icon-basic-elaboration-tablet-pencil',
        'icon-basic-elaboration-tablet-picture',
        'icon-basic-elaboration-tablet-refresh',
        'icon-basic-elaboration-tablet-search',
        'icon-basic-elaboration-todolist-2',
        'icon-basic-elaboration-todolist-check',
        'icon-basic-elaboration-todolist-cloud',
        'icon-basic-elaboration-todolist-download',
        'icon-basic-elaboration-todolist-flagged',
        'icon-basic-elaboration-todolist-minus',
        'icon-basic-elaboration-todolist-noaccess',
        'icon-basic-elaboration-todolist-pencil',
        'icon-basic-elaboration-todolist-plus',
        'icon-basic-elaboration-todolist-refresh',
        'icon-basic-elaboration-todolist-remove',
        'icon-basic-elaboration-todolist-search',
        'icon-basic-elaboration-todolist-star',
        'icon-basic-elaboration-todolist-upload',
        /* Linea eCommerce */
        'icon-ecommerce-bag',
        'icon-ecommerce-bag-check',
        'icon-ecommerce-bag-cloud',
        'icon-ecommerce-bag-download',
        'icon-ecommerce-bag-minus',
        'icon-ecommerce-bag-plus',
        'icon-ecommerce-bag-refresh',
        'icon-ecommerce-bag-remove',
        'icon-ecommerce-bag-search',
        'icon-ecommerce-bag-upload',
        'icon-ecommerce-banknote',
        'icon-ecommerce-banknotes',
        'icon-ecommerce-basket',
        'icon-ecommerce-basket-check',
        'icon-ecommerce-basket-cloud',
        'icon-ecommerce-basket-download',
        'icon-ecommerce-basket-minus',
        'icon-ecommerce-basket-plus',
        'icon-ecommerce-basket-refresh',
        'icon-ecommerce-basket-remove',
        'icon-ecommerce-basket-search',
        'icon-ecommerce-basket-upload',
        'icon-ecommerce-bath',
        'icon-ecommerce-cart',
        'icon-ecommerce-cart-check',
        'icon-ecommerce-cart-cloud',
        'icon-ecommerce-cart-content',
        'icon-ecommerce-cart-download',
        'icon-ecommerce-cart-minus',
        'icon-ecommerce-cart-plus',
        'icon-ecommerce-cart-refresh',
        'icon-ecommerce-cart-remove',
        'icon-ecommerce-cart-search',
        'icon-ecommerce-cart-upload',
        'icon-ecommerce-cent',
        'icon-ecommerce-colon',
        'icon-ecommerce-creditcard',
        'icon-ecommerce-diamond',
        'icon-ecommerce-dollar',
        'icon-ecommerce-euro',
        'icon-ecommerce-franc',
        'icon-ecommerce-gift',
        'icon-ecommerce-graph1',
        'icon-ecommerce-graph2',
        'icon-ecommerce-graph3',
        'icon-ecommerce-graph-decrease',
        'icon-ecommerce-graph-increase',
        'icon-ecommerce-guarani',
        'icon-ecommerce-kips',
        'icon-ecommerce-lira',
        'icon-ecommerce-megaphone',
        'icon-ecommerce-money',
        'icon-ecommerce-naira',
        'icon-ecommerce-pesos',
        'icon-ecommerce-pound',
        'icon-ecommerce-receipt',
        'icon-ecommerce-receipt-bath',
        'icon-ecommerce-receipt-cent',
        'icon-ecommerce-receipt-dollar',
        'icon-ecommerce-receipt-euro',
        'icon-ecommerce-receipt-franc',
        'icon-ecommerce-receipt-guarani',
        'icon-ecommerce-receipt-kips',
        'icon-ecommerce-receipt-lira',
        'icon-ecommerce-receipt-naira',
        'icon-ecommerce-receipt-pesos',
        'icon-ecommerce-receipt-pound',
        'icon-ecommerce-receipt-rublo',
        'icon-ecommerce-receipt-rupee',
        'icon-ecommerce-receipt-tugrik',
        'icon-ecommerce-receipt-won',
        'icon-ecommerce-receipt-yen',
        'icon-ecommerce-receipt-yen2',
        'icon-ecommerce-recept-colon',
        'icon-ecommerce-rublo',
        'icon-ecommerce-rupee',
        'icon-ecommerce-safe',
        'icon-ecommerce-sale',
        'icon-ecommerce-sales',
        'icon-ecommerce-ticket',
        'icon-ecommerce-tugriks',
        'icon-ecommerce-wallet',
        'icon-ecommerce-won',
        'icon-ecommerce-yen',
        'icon-ecommerce-yen2',
        /* Linea Music */
        'icon-music-beginning-button',
        'icon-music-bell',
        'icon-music-cd',
        'icon-music-diapason',
        'icon-music-eject-button',
        'icon-music-end-button',
        'icon-music-fastforward-button',
        'icon-music-headphones',
        'icon-music-ipod',
        'icon-music-loudspeaker',
        'icon-music-microphone',
        'icon-music-microphone-old',
        'icon-music-mixer',
        'icon-music-mute',
        'icon-music-note-multiple',
        'icon-music-note-single',
        'icon-music-pause-button',
        'icon-music-play-button',
        'icon-music-playlist',
        'icon-music-radio-ghettoblaster',
        'icon-music-radio-portable',
        'icon-music-record',
        'icon-music-recordplayer',
        'icon-music-repeat-button',
        'icon-music-rewind-button',
        'icon-music-shuffle-button',
        'icon-music-stop-button',
        'icon-music-tape',
        'icon-music-volume-down',
        'icon-music-volume-up',
        /* Linea Software */
        'icon-software-add-vectorpoint',
        'icon-software-box-oval',
        'icon-software-box-polygon',
        'icon-software-box-rectangle',
        'icon-software-box-roundedrectangle',
        'icon-software-character',
        'icon-software-crop',
        'icon-software-eyedropper',
        'icon-software-font-allcaps',
        'icon-software-font-baseline-shift',
        'icon-software-font-horizontal-scale',
        'icon-software-font-kerning',
        'icon-software-font-leading',
        'icon-software-font-size',
        'icon-software-font-smallcapital',
        'icon-software-font-smallcaps',
        'icon-software-font-strikethrough',
        'icon-software-font-tracking',
        'icon-software-font-underline',
        'icon-software-font-vertical-scale',
        'icon-software-horizontal-align-center',
        'icon-software-horizontal-align-left',
        'icon-software-horizontal-align-right',
        'icon-software-horizontal-distribute-center',
        'icon-software-horizontal-distribute-left',
        'icon-software-horizontal-distribute-right',
        'icon-software-indent-firstline',
        'icon-software-indent-left',
        'icon-software-indent-right',
        'icon-software-lasso',
        'icon-software-layers1',
        'icon-software-layers2',
        'icon-software-layout',
        'icon-software-layout-2columns',
        'icon-software-layout-3columns',
        'icon-software-layout-4boxes',
        'icon-software-layout-4columns',
        'icon-software-layout-4lines',
        'icon-software-layout-8boxes',
        'icon-software-layout-header',
        'icon-software-layout-header-2columns',
        'icon-software-layout-header-3columns',
        'icon-software-layout-header-4boxes',
        'icon-software-layout-header-4columns',
        'icon-software-layout-header-complex',
        'icon-software-layout-header-complex2',
        'icon-software-layout-header-complex3',
        'icon-software-layout-header-complex4',
        'icon-software-layout-header-sideleft',
        'icon-software-layout-header-sideright',
        'icon-software-layout-sidebar-left',
        'icon-software-layout-sidebar-right',
        'icon-software-magnete',
        'icon-software-pages',
        'icon-software-paintbrush',
        'icon-software-paintbucket',
        'icon-software-paintroller',
        'icon-software-paragraph',
        'icon-software-paragraph-align-left',
        'icon-software-paragraph-align-right',
        'icon-software-paragraph-center',
        'icon-software-paragraph-justify-all',
        'icon-software-paragraph-justify-center',
        'icon-software-paragraph-justify-left',
        'icon-software-paragraph-justify-right',
        'icon-software-paragraph-space-after',
        'icon-software-paragraph-space-before',
        'icon-software-pathfinder-exclude',
        'icon-software-pathfinder-intersect',
        'icon-software-pathfinder-subtract',
        'icon-software-pathfinder-unite',
        'icon-software-pen',
        'icon-software-pen-add',
        'icon-software-pen-remove',
        'icon-software-pencil',
        'icon-software-polygonallasso',
        'icon-software-reflect-horizontal',
        'icon-software-reflect-vertical',
        'icon-software-remove-vectorpoint',
        'icon-software-scale-expand',
        'icon-software-scale-reduce',
        'icon-software-selection-oval',
        'icon-software-selection-polygon',
        'icon-software-selection-rectangle',
        'icon-software-selection-roundedrectangle',
        'icon-software-shape-oval',
        'icon-software-shape-polygon',
        'icon-software-shape-rectangle',
        'icon-software-shape-roundedrectangle',
        'icon-software-slice',
        'icon-software-transform-bezier',
        'icon-software-vector-box',
        'icon-software-vector-composite',
        'icon-software-vector-line',
        'icon-software-vertical-align-bottom',
        'icon-software-vertical-align-center',
        'icon-software-vertical-align-top',
        'icon-software-vertical-distribute-bottom',
        'icon-software-vertical-distribute-center',
        'icon-software-vertical-distribute-top',
        /* Linea Weather */
        'icon-weather-aquarius',
        'icon-weather-aries',
        'icon-weather-cancer',
        'icon-weather-capricorn',
        'icon-weather-cloud',
        'icon-weather-cloud-drop',
        'icon-weather-cloud-lightning',
        'icon-weather-cloud-snowflake',
        'icon-weather-downpour-fullmoon',
        'icon-weather-downpour-halfmoon',
        'icon-weather-downpour-sun',
        'icon-weather-drop',
        'icon-weather-first-quarter',
        'icon-weather-fog',
        'icon-weather-fog-fullmoon',
        'icon-weather-fog-halfmoon',
        'icon-weather-fog-sun',
        'icon-weather-fullmoon',
        'icon-weather-gemini',
        'icon-weather-hail',
        'icon-weather-hail-fullmoon',
        'icon-weather-hail-halfmoon',
        'icon-weather-hail-sun',
        'icon-weather-last-quarter',
        'icon-weather-leo',
        'icon-weather-libra',
        'icon-weather-lightning',
        'icon-weather-mistyrain',
        'icon-weather-mistyrain-fullmoon',
        'icon-weather-mistyrain-halfmoon',
        'icon-weather-mistyrain-sun',
        'icon-weather-moon',
        'icon-weather-moondown-full',
        'icon-weather-moondown-half',
        'icon-weather-moonset-full',
        'icon-weather-moonset-half',
        'icon-weather-move2',
        'icon-weather-newmoon',
        'icon-weather-pisces',
        'icon-weather-rain',
        'icon-weather-rain-fullmoon',
        'icon-weather-rain-halfmoon',
        'icon-weather-rain-sun',
        'icon-weather-sagittarius',
        'icon-weather-scorpio',
        'icon-weather-snow',
        'icon-weather-snow-fullmoon',
        'icon-weather-snow-halfmoon',
        'icon-weather-snow-sun',
        'icon-weather-snowflake',
        'icon-weather-star',
        'icon-weather-storm-11',
        'icon-weather-storm-32',
        'icon-weather-storm-fullmoon',
        'icon-weather-storm-halfmoon',
        'icon-weather-storm-sun',
        'icon-weather-sun',
        'icon-weather-sundown',
        'icon-weather-sunset',
        'icon-weather-taurus',
        'icon-weather-tempest',
        'icon-weather-tempest-fullmoon',
        'icon-weather-tempest-halfmoon',
        'icon-weather-tempest-sun',
        'icon-weather-variable-fullmoon',
        'icon-weather-variable-halfmoon',
        'icon-weather-variable-sun',
        'icon-weather-virgo',
        'icon-weather-waning-cresent',
        'icon-weather-waning-gibbous',
        'icon-weather-waxing-cresent',
        'icon-weather-waxing-gibbous',
        'icon-weather-wind',
        'icon-weather-wind-e',
        'icon-weather-wind-fullmoon',
        'icon-weather-wind-halfmoon',
        'icon-weather-wind-n',
        'icon-weather-wind-ne',
        'icon-weather-wind-nw',
        'icon-weather-wind-s',
        'icon-weather-wind-se',
        'icon-weather-wind-sun',
        'icon-weather-wind-sw',
        'icon-weather-wind-w',
        'icon-weather-windgust',
    ];
}
