<?php

function themo_icons() {
    return [
        'th-trip travelpack-aqualung-bottles' => 'aqualung-bottles',
        'th-trip travelpack-baseball-headgear' => 'baseball-headgear',
        'th-trip travelpack-beach-bag' => 'each-bag',
        'th-trip travelpack-beach-ball' => 'beach-ball',
        'th-trip travelpack-beach-mattress' => 'beach-mattress',
        'th-trip travelpack-big-trip-caravan' => 'big-trip-caravan',
        'th-trip travelpack-binoculars' => 'binoculars',
        'th-trip travelpack-boat-anchor' => 'boat-anchor',
        'th-trip travelpack-cableway-lift' => 'cableway-lift',
        'th-trip travelpack-cadillac-car' => 'cadillac-car',
        'th-trip travelpack-camel-walking' => 'camel-walking',
        'th-trip travelpack-camping-tent' => 'camping-tent',
        'th-trip travelpack-car-trip' => 'car-trip',
        'th-trip travelpack-carnival-masks' => 'carnival-masks',
        'th-trip travelpack-circular-watch' => 'circular-watch',
        'th-trip travelpack-concert-tickets' => 'oncert-tickets',
        'th-trip travelpack-construction-jacket' => 'construction-jacket',
        'th-trip travelpack-cruise-liner-boat' => 'ruise-liner-boat',
        'th-trip travelpack-digital-photography-camera' => 'digital-photography-camera',
        'th-trip travelpack-direction-sign' => 'direction-sign',
        'th-trip travelpack-double-dice' => 'double-dice',
        'th-trip travelpack-dubai-burj-al-arab' => 'dubai-burj-al-arab',
        'th-trip travelpack-extensible-pirate-spyglass' => 'extensible-pirate-spyglass',
        'th-trip travelpack-female-swim-suit' => 'female-swim-suit',
        'th-trip travelpack-film-roll' => 'film-roll',
        'th-trip travelpack-flip-flops-top-view' => 'flip-flops-top-view',
        'th-trip travelpack-flippers' => 'flippers',
        'th-trip travelpack-flying-helicopter' => 'flying-helicopter',
        'th-trip travelpack-flying-kite' => 'flying-kite',
        'th-trip travelpack-fork-plate-knife' => 'fork-plate-knife',
        'th-trip travelpack-french-eiffel-tower' => 'french-eiffel-tower',
        'th-trip travelpack-frontal-reflex-camera' => 'frontal-reflex-camera',
        'th-trip travelpack-frontal-school-bus' => 'frontal-school-bus',
        'th-trip travelpack-frontal-train' => 'frontal-train',
        'th-trip travelpack-frontal-video-camera' => 'frontal-video-camera',
        'th-trip travelpack-gym-dumbbell' => 'gym-dumbbell',
        'th-trip travelpack-hand-fan' => 'hand-fan',
        'th-trip travelpack-hanger-with-towel' => 'hanger-with-towel',
        'th-trip travelpack-high-speed-train' => 'high-speed-train',
        'th-trip travelpack-hot-air-baloon-flying' => 'hot-air-baloon-flying',
        'th-trip travelpack-hotel-key' => 'hotel-key',
        'th-trip travelpack-indian-tent' => 'indian-tent',
        'th-trip travelpack-inflatable-boat-top-view' => 'inflatable-boat-top-view',
        'th-trip travelpack-jellyfish' => 'jellyfish',
        'th-trip travelpack-journey-bag' => 'journey-bag',
        'th-trip travelpack-kayak-top-view' => 'kayak-top-view',
        'th-trip travelpack-king-size-bed' => 'king-size-bed',
        'th-trip travelpack-lifebuoy' => 'lifebuoy',
        'th-trip travelpack-luggage-cart' => 'luggage-cart',
        'th-trip travelpack-map-pin' => 'map-pin',
        'th-trip travelpack-martini-glass' => 'martini-glass',
        'th-trip travelpack-mosque-construction' => 'mosque-construction',
        'th-trip travelpack-motorbiking-trip' => 'motorbiking-trip',
        'th-trip travelpack-motorcycle-helmet' => 'motorcycle-helmet',
        'th-trip travelpack-mountains-with-snow' => 'mountains-with-snow',
        'th-trip travelpack-movie-photogram' => 'movie-photogram',
        'th-trip travelpack-open-umbrella' => 'open-umbrella',
        'th-trip travelpack-orientation-compass' => 'orientation-compass',
        'th-trip travelpack-party-drink' => 'party-drink',
        'th-trip travelpack-passports' => 'passports',
        'th-trip travelpack-petrol-station' => 'petrol-station',
        'th-trip travelpack-ping-pong-rackets' => 'ping-pong-rackets',
        'th-trip travelpack-pisa-tower' => 'pisa-tower',
        'th-trip travelpack-polaroid-pictures' => 'polaroid-pictures',
        'th-trip travelpack-postal-stamp' => 'postal-stamp',
        'th-trip travelpack-pyramids-of-egypt' => 'pyramids-of-egypt',
        'th-trip travelpack-reading-glasses' => 'reading-glasses',
        'th-trip travelpack-reception-bell' => 'reception-bell',
        'th-trip travelpack-retro-bicycle' => 'retro-bicycle',
        'th-trip travelpack-room-service' => 'room-service',
        'th-trip travelpack-safety-box' => 'safety-box',
        'th-trip travelpack-sailing-yacht' => 'sailing-yacht',
        'th-trip travelpack-scooter' => 'scooter',
        'th-trip travelpack-scuba-mask' => 'scuba-mask',
        'th-trip travelpack-sea-horse' => 'sea-horse',
        'th-trip travelpack-sea-shell' => 'sea-shell',
        'th-trip travelpack-ship-steering-wheel' => 'ship-steering-wheel',
        'th-trip travelpack-shower-head-running-water' => 'shower-head-running-water',
        'th-trip travelpack-skis-and-sticks' => 'skis-and-sticks',
        'th-trip travelpack-snowboard-with-boot' => 'snowboard-with-boot',
        'th-trip travelpack-snowmobile' => 'snowmobile',
        'th-trip travelpack-starfish' => 'starfish',
        'th-trip travelpack-suitcase-with-wheels' => 'suitcase-with-wheels',
        'th-trip travelpack-suitcase-with-wheels-1' => 'suitcase-with-wheels-1',
        'th-trip travelpack-summer-sun' => 'summer-sun',
        'th-trip travelpack-sunbed' => 'sunbed',
        'th-trip travelpack-surf-board' => 'surf-board',
        'th-trip travelpack-swimming-trunks' => 'swimming-trunks',
        'th-trip travelpack-taxi-sign' => 'taxi-sign',
        'th-trip travelpack-tennis-equipment' => 'tennis-equipment',
        'th-trip travelpack-travelling-backpack' => 'travelling-backpack',
        'th-trip travelpack-trifolded-map-route' => 'trifolded-map-route',
        'th-trip travelpack-trip-bag' => 'trip-bag',
        'th-trip travelpack-tropical-fish' => 'tropical-fish',
        'th-trip travelpack-two-credit-cards' => 'two-credit-cards',
        'th-trip travelpack-two-palm-trees-island' => 'two-palm-trees-island',
        'th-trip travelpack-women-hat' => 'women-hat',
        'th-trip travelpack-world-wide-web' => 'world-wide-web',
    ];
}

function themo_fa_icons() {
    return [
        'th-trip travelpack-aqualung-bottles',
        'th-trip travelpack-baseball-headgear',
        'th-trip travelpack-beach-bag',
        'th-trip travelpack-beach-ball',
        'th-trip travelpack-beach-mattress',
        'th-trip travelpack-big-trip-caravan',
        'th-trip travelpack-binoculars',
        'th-trip travelpack-boat-anchor',
        'th-trip travelpack-cableway-lift',
        'th-trip travelpack-cadillac-car',
        'th-trip travelpack-camel-walking',
        'th-trip travelpack-camping-tent',
        'th-trip travelpack-car-trip',
        'th-trip travelpack-carnival-masks',
        'th-trip travelpack-circular-watch',
        'th-trip travelpack-concert-tickets',
        'th-trip travelpack-construction-jacket',
        'th-trip travelpack-cruise-liner-boat',
        'th-trip travelpack-digital-photography-camera',
        'th-trip travelpack-direction-sign',
        'th-trip travelpack-double-dice',
        'th-trip travelpack-dubai-burj-al-arab',
        'th-trip travelpack-extensible-pirate-spyglass',
        'th-trip travelpack-female-swim-suit',
        'th-trip travelpack-film-roll',
        'th-trip travelpack-flip-flops-top-view',
        'th-trip travelpack-flippers',
        'th-trip travelpack-flying-helicopter',
        'th-trip travelpack-flying-kite',
        'th-trip travelpack-fork-plate-knife',
        'th-trip travelpack-french-eiffel-tower',
        'th-trip travelpack-frontal-reflex-camera',
        'th-trip travelpack-frontal-school-bus',
        'th-trip travelpack-frontal-train',
        'th-trip travelpack-frontal-video-camera',
        'th-trip travelpack-gym-dumbbell',
        'th-trip travelpack-hand-fan',
        'th-trip travelpack-hanger-with-towel',
        'th-trip travelpack-high-speed-train',
        'th-trip travelpack-hot-air-baloon-flying',
        'th-trip travelpack-hotel-key',
        'th-trip travelpack-indian-tent',
        'th-trip travelpack-inflatable-boat-top-view',
        'th-trip travelpack-jellyfish',
        'th-trip travelpack-journey-bag',
        'th-trip travelpack-kayak-top-view',
        'th-trip travelpack-king-size-bed',
        'th-trip travelpack-lifebuoy',
        'th-trip travelpack-luggage-cart',
        'th-trip travelpack-map-pin',
        'th-trip travelpack-martini-glass',
        'th-trip travelpack-mosque-construction',
        'th-trip travelpack-motorbiking-trip',
        'th-trip travelpack-motorcycle-helmet',
        'th-trip travelpack-mountains-with-snow',
        'th-trip travelpack-movie-photogram',
        'th-trip travelpack-open-umbrella',
        'th-trip travelpack-orientation-compass',
        'th-trip travelpack-party-drink',
        'th-trip travelpack-passports',
        'th-trip travelpack-petrol-station',
        'th-trip travelpack-ping-pong-rackets',
        'th-trip travelpack-pisa-tower',
        'th-trip travelpack-polaroid-pictures',
        'th-trip travelpack-postal-stamp',
        'th-trip travelpack-pyramids-of-egypt',
        'th-trip travelpack-reading-glasses',
        'th-trip travelpack-reception-bell',
        'th-trip travelpack-retro-bicycle',
        'th-trip travelpack-room-service',
        'th-trip travelpack-safety-box',
        'th-trip travelpack-sailing-yacht',
        'th-trip travelpack-scooter',
        'th-trip travelpack-scuba-mask',
        'th-trip travelpack-sea-horse',
        'th-trip travelpack-sea-shell',
        'th-trip travelpack-ship-steering-wheel',
        'th-trip travelpack-shower-head-running-water',
        'th-trip travelpack-skis-and-sticks',
        'th-trip travelpack-snowboard-with-boot',
        'th-trip travelpack-snowmobile',
        'th-trip travelpack-starfish',
        'th-trip travelpack-suitcase-with-wheels',
        'th-trip travelpack-suitcase-with-wheels-1',
        'th-trip travelpack-summer-sun',
        'th-trip travelpack-sunbed',
        'th-trip travelpack-surf-board',
        'th-trip travelpack-swimming-trunks',
        'th-trip travelpack-taxi-sign',
        'th-trip travelpack-tennis-equipment',
        'th-trip travelpack-travelling-backpack',
        'th-trip travelpack-trifolded-map-route',
        'th-trip travelpack-trip-bag',
        'th-trip travelpack-tropical-fish',
        'th-trip travelpack-two-credit-cards',
        'th-trip travelpack-two-palm-trees-island',
        'th-trip travelpack-women-hat',
        'th-trip travelpack-world-wide-web',
        'fa fa-facebook',
        'fa fa-facebook-official',
        'fa fa-facebook-square',
        'fa fa-google',
        'fa fa-google-plus',
        'fa fa-google-plus-official',
        'fa fa-google-plus-square',
        'fa fa-instagram',
        'fa fa-linkedin',
        'fa fa-linkedin-square',
        'fa fa-pinterest',
        'fa fa-pinterest-p',
        'fa fa-pinterest-square',
        'fa fa-slack',
        'fa fa-twitter',
        'fa fa-twitter-square',
        'fa fa-youtube',
        'fa fa-youtube-play',
        'fa fa-youtube-square',
    ];
}
